"use client";
import { care } from "@/lib/care-client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { Download, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { vault, fileSize, label, type DocumentRecord, type Metadata } from "@/lib/vault-client";
import { ExtractionPanel } from "./extraction-panel";
import { reviewClient } from "@/lib/review-client";
import type { Source } from "@/lib/extraction-client";
import { MetadataFields, cleanMetadata, emptyMetadata } from "./metadata-fields";
export function DocumentViewer({ id }: { id: string }) {
  const dirty = useRef(false); const previewSection = useRef<HTMLElement>(null); const [source, setSource] = useState<Source | null>(null);
  const router = useRouter(); const [document, setDocument] = useState<DocumentRecord | null>(null); const [metadata, setMetadata] = useState<Metadata>(emptyMetadata);
  const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0);
  const [page, setPage] = useState(() => { if (typeof window === "undefined") return 1; const n = Number(new URLSearchParams(window.location.search).get("page")); return Number.isInteger(n) && n > 0 && n <= 200 ? n : 1; }); const [preview, setPreview] = useState(""); const [previewError, setPreviewError] = useState(""); const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { let active = true; vault.get(id).then((d) => { if (active) { setDocument((previous) => dirty.current && previous ? { ...previous, status: d.status } : d); if (!dirty.current) setMetadata(d); setError(""); } }).catch((e: unknown) => { if (active) setError(e instanceof Error ? e.message : "Document unavailable."); }); return () => { active = false; }; }, [id, revision]);
  useEffect(() => {
    if (!document) return; const controller = new AbortController(); let url = "";
    vault.preview(id, page, controller.signal).then((blob) => { if (!controller.signal.aborted) { url = URL.createObjectURL(blob); setPreview(url); } }).catch((e: unknown) => { if (!controller.signal.aborted) setPreviewError(e instanceof Error ? e.message : "Preview unavailable."); });
    return () => { controller.abort(); if (url) URL.revokeObjectURL(url); };
  }, [id, page, document]);
  useEffect(() => {
    const candidate = new URLSearchParams(window.location.search).get("candidate"); if (!candidate) return;
    let active = true; reviewClient.get(candidate).then((c) => { if (active && c.documentId === id) { setSource(c.extracted.source); setPage(c.extracted.source.page); setPreview(""); } }).catch(() => { if (active) setError("Source evidence is unavailable."); });
    return () => { active = false; };
  }, [id]);
  async function save(event: React.FormEvent) { event.preventDefault(); if (!document) return; setBusy(true); setError(""); setMessage(""); try { const next = await vault.update(id, document.version, cleanMetadata(metadata)); setDocument(next); setMetadata(next); dirty.current = false; setMessage("Metadata saved."); } catch (e) { setError(e instanceof Error ? e.message : "Save failed."); } finally { setBusy(false); } }
  async function download() { if (!document) return; setBusy(true); setError(""); try { await vault.download(document); } catch (e) { setError(e instanceof Error ? e.message : "Download unavailable."); } finally { setBusy(false); } }
  async function remove() { setBusy(true); setError(""); try { const purged = await vault.remove(id); dialog.current?.close(); router.replace(`/records?deleted=${purged ? "complete" : "pending"}`); } catch (e) { setError(e instanceof Error ? e.message : "Deletion failed."); dialog.current?.close(); } finally { setBusy(false); } }
  return <><Link href="/records" className="text-sm font-medium text-primary">← All records</Link>{error && <p role="alert" className="my-5 rounded-lg bg-red-50 p-4 text-red-900">{error} <button className="underline" onClick={() => { dirty.current = false; setRevision((v) => v + 1); }}>Reload</button></p>}
    {!document ? !error && <div className="mt-8 h-64 rounded-xl bg-muted motion-safe:animate-pulse" role="status" aria-label="Loading document" /> : <>
      <div className="my-7 flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><p className="text-xs uppercase tracking-widest text-primary">Private document</p><h1 className="mt-2 break-all text-2xl font-semibold">{document.originalFilename}</h1><p className="mt-2 text-sm text-muted-foreground">{label(document.documentType)} · {fileSize(document.byteSize)} · {label(document.status)}</p></div><div className="flex gap-2"><Button variant="outline" disabled={busy} onClick={download}><Download size={16} aria-hidden="true" />Download original</Button><Button variant="outline" disabled={busy} onClick={() => dialog.current?.showModal()}><Trash2 size={16} aria-hidden="true" />Delete</Button></div></div>
      <div className="grid items-start gap-7 lg:grid-cols-[minmax(0,1.4fr)_minmax(300px,1fr)]"><section className="overflow-hidden rounded-xl border border-border bg-white" aria-label="Document preview" ref={previewSection} tabIndex={-1}>
        <div className="flex items-center justify-between border-b border-border p-3"><Button variant="outline" size="sm" disabled={page === 1} onClick={() => { setPreview(""); setPreviewError(""); setPage((p) => p - 1); }}>Previous</Button><span className="text-sm">Page {page} of {document.pageCount}</span><Button variant="outline" size="sm" disabled={page === document.pageCount} onClick={() => { setPreview(""); setPreviewError(""); setPage((p) => p + 1); }}>Next</Button></div>
        {source && source.page === page && <div className="border-b border-border bg-amber-50 p-4 text-sm"><p className="font-medium">Source evidence · page {source.page}</p><pre className="mt-2 whitespace-pre-wrap break-words font-sans">{source.text}</pre><p className="mt-2 text-xs text-muted-foreground">{source.method === "TESSERACT_OCR" ? "OCR transcript; compare with the image below." : "Text from the original PDF."}</p></div>}
        {previewError ? <p role="alert" className="p-6 text-red-800">{previewError}</p> : preview ? <Image src={preview} alt={`Preview of ${document.originalFilename}, page ${page}`} width={1200} height={1600} unoptimized className="h-auto w-full" /> : <div role="status" className="m-6 h-96 rounded bg-muted motion-safe:animate-pulse"><span className="sr-only">Loading secure preview</span></div>}
        <p className="border-t border-border p-3 text-xs text-muted-foreground">{document.mimeType === "application/pdf" ? "PDF pages are rendered as images for safe viewing. Download preserves the original PDF." : "Preview of your uploaded image."}</p>
      </section><section className="rounded-xl border border-border bg-white p-5"><h2 className="mb-5 text-lg font-semibold">Document details</h2><form onSubmit={save} className="space-y-5"><MetadataFields value={metadata} onChange={(value) => { dirty.current = true; setMetadata(value); }} disabled={busy} /><Button disabled={busy} type="submit">Save metadata</Button>{message && <p role="status" className="text-sm text-primary">{message}</p>}</form><dl className="mt-7 space-y-4 border-t border-border pt-5 text-sm"><div><dt className="font-medium">Uploaded</dt><dd className="mt-1 text-muted-foreground">{new Date(document.uploadedAt).toLocaleString()}</dd></div><div><dt className="font-medium">Integrity fingerprint · SHA-256</dt><dd className="mt-1 break-all font-mono text-xs text-muted-foreground">{document.sha256}</dd></div></dl><p className="mt-5 text-xs leading-relaxed text-muted-foreground">Only your account can access this document. It is not automatically shared. Processing creates unverified candidates and never shares your file.</p></section></div>
      <div className="my-4 flex flex-wrap items-center gap-4"><Button variant="outline" disabled={busy} onClick={async () => { setBusy(true); try { await care.detect(id); setMessage("Follow-up check complete. Open Follow-ups to review any scheduling instructions."); } catch { setError("Follow-up check unavailable. Process the document first or retry."); } finally { setBusy(false); } }}>Check follow-ups</Button><Link href="/follow-ups" className="text-sm text-primary underline">Review possible follow-ups</Link></div><ExtractionPanel id={id} onStateChange={() => setRevision((v) => v + 1)} onSource={(evidence) => { setSource(evidence); if (page !== evidence.page) { setPreview(""); setPreviewError(""); setPage(evidence.page); } previewSection.current?.scrollIntoView({ behavior: "smooth", block: "start" }); previewSection.current?.focus({ preventScroll: true }); }} />
      <dialog ref={dialog} className="m-auto w-[min(90vw,440px)] rounded-xl border border-border bg-white p-6 text-foreground backdrop:bg-black/40" aria-labelledby="delete-title"><h2 id="delete-title" className="text-xl font-semibold">Delete this document?</h2><p className="my-4 text-sm leading-relaxed text-muted-foreground">This removes the document from your account immediately. The stored original is deleted; if storage is temporarily unavailable, deletion is queued and retried. Generated Visit Packs retain their historical snapshots; delete those packs separately to remove those copies. This cannot be undone.</p><div className="flex justify-end gap-3"><Button variant="outline" disabled={busy} onClick={() => dialog.current?.close()}>Keep document</Button><Button disabled={busy} onClick={remove}>{busy ? "Deleting…" : "Delete document"}</Button></div></dialog>
    </>}</>;
}
