package com.carepath.care;
import static com.carepath.care.CareDtos.*;import static com.carepath.care.CareSupport.*;import static com.carepath.audit.AuditService.Action.*;
import java.util.*;import java.sql.*;import java.time.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.carepath.longitudinal.HistoryDtos.Page;import com.carepath.audit.AuditService;
@Service @Transactional
public class AppointmentService {
 private final CareSupport s;private final AuditService audit;private final ReminderService reminders;
 public AppointmentService(CareSupport s,AuditService a,ReminderService r){this.s=s;audit=a;reminders=r;}
 private List<UUID> links(String type,UUID id,UUID owner){return s.db.query("SELECT "+type+"_id FROM appointment_"+type+" WHERE appointment_id=? AND owner_id=? ORDER BY "+type+"_id",(r,n)->r.getObject(1,UUID.class),id,owner);}
 private Appointment map(ResultSet r,int n)throws SQLException{UUID id=r.getObject("id",UUID.class),owner=r.getObject("owner_id",UUID.class);return new Appointment(id,r.getString("provider_name"),r.getString("specialty"),time(r,"starts_at"),r.getString("time_zone"),r.getString("location"),r.getString("phone"),r.getString("external_url"),r.getString("notes"),r.getString("status"),r.getObject("follow_up_date",LocalDate.class),r.getLong("version"),links("document",id,owner),links("symptom",id,owner),links("question",id,owner),s.db.query("SELECT offset_minutes FROM reminder WHERE appointment_id=? AND owner_id=? AND status<>'CANCELLED' ORDER BY offset_minutes",(rs,i)->rs.getInt(1),id,owner));}
 public Appointment get(UUID id){return s.db.query("SELECT * FROM appointment WHERE id=? AND owner_id=?",this::map,id,s.owner()).stream().findFirst().orElseThrow(CareSupport::missing);}
 public Page<Appointment> list(String scope,int page){if(!Set.of("ALL","UPCOMING","PAST").contains(scope))throw invalid();String w="owner_id=?";List<Object> a=new ArrayList<>();a.add(s.owner());if(!scope.equals("ALL")){w+=scope.equals("UPCOMING")?" AND status='SCHEDULED' AND starts_at>=?":" AND starts_at<?";a.add(utc(s.clock.instant()));}long total=s.db.queryForObject("SELECT count(*) FROM appointment WHERE "+w,Long.class,a.toArray());a.add(page*20L);return new Page<>(s.db.query("SELECT * FROM appointment WHERE "+w+" ORDER BY starts_at"+(scope.equals("PAST")?" DESC":"")+",id LIMIT 20 OFFSET ?",this::map,a.toArray()),total,page,20);}
 private void setLinks(String type,String table,UUID id,UUID owner,List<UUID> ids){for(UUID link:new LinkedHashSet<>(ids))s.own(table,link,owner);s.db.update("DELETE FROM appointment_"+type+" WHERE appointment_id=? AND owner_id=?",id,owner);for(UUID link:new LinkedHashSet<>(ids)){if(type.equals("question"))s.db.update("INSERT INTO appointment_question(appointment_id,owner_id,question_id) VALUES(?,?,?)",id,owner,link);else s.db.update("INSERT INTO appointment_"+type+"(id,appointment_id,owner_id,"+type+"_id) VALUES(?,?,?,?)",UUID.randomUUID(),id,owner,link);}}
 public Appointment save(UUID id,AppointmentInput x){Instant when=instant(x.startsAt(),x.timeZone());url(x.externalUrl());ReminderService.offsets(x.offsets());if(x.followUpDate()!=null&&x.followUpDate().isBefore(x.startsAt().toLocalDate()))throw invalid();UUID owner=s.owner();boolean create=id==null;if(create){id=UUID.randomUUID();s.db.update("INSERT INTO appointment(id,owner_id,provider_name,starts_at,time_zone) VALUES(?,?,?,?,?)",id,owner,x.providerName().strip(),utc(when),x.timeZone());}else{s.lock("appointment",id,owner);var old=get(id);if(old.version()!=x.version()||!old.status().equals("SCHEDULED"))throw conflict();}
 s.db.update("UPDATE appointment SET provider_name=?,specialty=?,starts_at=?,time_zone=?,location=?,phone=?,external_url=?,notes=?,follow_up_date=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_id=?",x.providerName().strip(),x.specialty(),utc(when),x.timeZone(),x.location(),x.phone(),x.externalUrl(),x.notes(),x.followUpDate(),id,owner);
 setLinks("document","medical_document",id,owner,x.documentIds());setLinks("symptom","symptom",id,owner,x.symptomIds());setLinks("question","saved_question",id,owner,x.questionIds());reminders.replace(owner,id,true,when,x.offsets());audit.care(owner,create?APPOINTMENT_CREATED:APPOINTMENT_UPDATED,"APPOINTMENT",id,false);return get(id);}
 public Appointment action(UUID id,Action x){s.lock("appointment",id,s.owner());var old=get(id);if(old.status().equals(x.status().name()))return old;if(old.version()!=x.version()||!old.status().equals("SCHEDULED")||x.status()==AppointmentStatus.SCHEDULED)throw conflict();s.db.update("UPDATE appointment SET status=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_id=?",x.status().name(),id,s.owner());reminders.cancel(s.owner(),id,true);audit.care(s.owner(),x.status()==AppointmentStatus.CANCELLED?APPOINTMENT_CANCELLED:APPOINTMENT_COMPLETED,"APPOINTMENT",id,false);return get(id);}
 public void delete(UUID id){s.lock("appointment",id,s.owner());s.db.update("DELETE FROM appointment WHERE id=? AND owner_id=?",id,s.owner());audit.care(s.owner(),APPOINTMENT_DELETED,"APPOINTMENT",id,false);}
}
