package com.carepath.care;
import static com.carepath.care.CareDtos.*;import static com.carepath.care.CareSupport.*;import static com.carepath.audit.AuditService.Action.*;
import java.util.*;import java.sql.*;import java.time.*;import java.security.*;import java.nio.charset.StandardCharsets;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.carepath.longitudinal.HistoryDtos.Page;import com.carepath.audit.AuditService;
@Service @Transactional
public class FollowUpService {
 private final CareSupport s;private final AuditService audit;private final ReminderService reminders;
 public FollowUpService(CareSupport s,AuditService a,ReminderService r){this.s=s;audit=a;reminders=r;}
 public void detectOwned(UUID document){detect(s.owner(),document);}
 // Called in the extraction publication transaction, while holding the document row lock.
 public void detect(UUID owner,UUID document){s.lock("medical_document",document,owner);LocalDate date=s.db.queryForObject("SELECT document_date FROM medical_document WHERE id=? AND owner_id=?",LocalDate.class,document,owner);
  var pages=s.db.query("SELECT id,page_number,extracted_text,extraction_method FROM document_page WHERE document_id=? AND owner_id=? ORDER BY page_number LIMIT 200",(r,n)->new Object[]{r.getObject(1,UUID.class),r.getInt(2),r.getString(3),r.getString(4)},document,owner);
  int detected=0;for(var page:pages){String text=(String)page[2];if(text==null)continue;for(String line:text.split("\\R")){var parsed=FollowUpParser.parse(line,date);if(parsed.isEmpty())continue;var x=parsed.get();if(++detected>100)return;String key=hash(page[1]+"|"+x.text());if(s.db.queryForObject("SELECT count(*) FROM follow_up WHERE document_id=? AND owner_id=? AND instruction_key=?",Long.class,document,owner,key)>0)continue;
   s.db.update("INSERT INTO follow_up(id,owner_id,document_id,page_id,source_text,anchor_date,interval_value,interval_unit,suggested_date,confidence,instruction_key) VALUES(?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID(),owner,document,page[0],x.text(),date,x.duration(),x.unit(),x.date(),x.confidence().equals("HIGH")&&!"TESSERACT_OCR".equals(page[3])?1:0.3,key);
  }}
 }
 private static String hash(String text){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(text.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
 private static final String BASE="SELECT f.*,p.page_number,d.original_filename FROM follow_up f JOIN document_page p ON p.id=f.page_id AND p.owner_id=f.owner_id JOIN medical_document d ON d.id=f.document_id AND d.owner_id=f.owner_id ";
 private FollowUp map(ResultSet r,int n)throws SQLException{return new FollowUp(r.getObject("id",UUID.class),r.getObject("document_id",UUID.class),r.getInt("page_number"),r.getString("original_filename"),r.getString("source_text"),r.getObject("anchor_date",LocalDate.class),(Integer)r.getObject("interval_value"),r.getString("interval_unit"),r.getObject("suggested_date",LocalDate.class),r.getObject("confirmed_date",LocalDate.class),time(r,"confirmed_at_time"),r.getString("time_zone"),r.getBigDecimal("confidence").doubleValue()>=.9?"HIGH":"LOW",r.getString("status"),r.getLong("version"));}
 public FollowUp get(UUID id){return s.db.query(BASE+"WHERE f.id=? AND f.owner_id=?",this::map,id,s.owner()).stream().findFirst().orElseThrow(CareSupport::missing);}
 public Page<FollowUp> list(int page,String scope){if(!Set.of("ALL","UPCOMING").contains(scope))throw invalid();String condition=scope.equals("UPCOMING")?" AND f.status IN ('CONFIRMED','EDITED') AND f.confirmed_at_time>=?":"";List<Object> args=new ArrayList<>();args.add(s.owner());if(scope.equals("UPCOMING"))args.add(utc(s.clock.instant()));long count=s.db.queryForObject("SELECT count(*) FROM follow_up f WHERE f.owner_id=?"+condition,Long.class,args.toArray());args.add(page*20L);return new Page<>(s.db.query(BASE+"WHERE f.owner_id=?"+condition+(scope.equals("UPCOMING")?" ORDER BY f.confirmed_at_time,f.id":" ORDER BY f.created_at DESC,f.id")+" LIMIT 20 OFFSET ?",this::map,args.toArray()),count,page,20);}
 public FollowUp decide(UUID id,FollowAction x){s.lock("follow_up",id,s.owner());var old=get(id);if(!old.status().equals("PENDING")){if(x.action().equals("IGNORE")&&old.status().equals("IGNORED"))return old;throw conflict();}if(old.version()!=x.version())throw conflict();if(x.action().equals("IGNORE")){s.db.update("UPDATE follow_up SET status='IGNORED',version=version+1 WHERE id=? AND owner_id=?",id,s.owner());audit.care(s.owner(),FOLLOW_UP_IGNORED,"FOLLOW_UP",id,false);}else{if(x.confirmedAt()==null||x.timeZone()==null)throw invalid();Instant when=instant(x.confirmedAt(),x.timeZone());ReminderService.offsets(x.offsets());LocalDate date=x.confirmedAt().toLocalDate();boolean edited=!Objects.equals(old.suggestedDate(),date);s.db.update("UPDATE follow_up SET confirmed_date=?,confirmed_at_time=?,time_zone=?,status=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_id=?",date,utc(when),x.timeZone(),edited?"EDITED":"CONFIRMED",id,s.owner());reminders.replace(s.owner(),id,false,when,x.offsets());audit.care(s.owner(),edited?FOLLOW_UP_EDITED:FOLLOW_UP_CONFIRMED,"FOLLOW_UP",id,false);}return get(id);}
}
