package com.carepath.care;
import static com.carepath.care.CareSupport.*;import static com.carepath.care.CareDtos.*;import static com.carepath.audit.AuditService.Action.*;
import java.util.*;import java.time.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.carepath.audit.AuditService;import com.carepath.longitudinal.HistoryDtos.Page;
@Service @Transactional
public class ReminderService {
 private final CareSupport s;private final AuditService audit;public ReminderService(CareSupport s,AuditService a){this.s=s;audit=a;}
 static void offsets(List<Integer> offsets){if(offsets==null||!Set.of(0,60,1440,2880,10080).containsAll(offsets)||new HashSet<>(offsets).size()!=offsets.size())throw invalid();}
 // Caller holds source-row lock. Source then reminder is the shared lock order.
 void replace(UUID owner,UUID id,boolean appointment,Instant when,List<Integer> offsets){offsets(offsets);String col=appointment?"appointment_id":"follow_up_id";var existing=s.db.query("SELECT offset_minutes,scheduled_at FROM reminder WHERE owner_id=? AND "+col+"=?",(r,n)->Map.entry(r.getInt(1),time(r,"scheduled_at")),owner,id);if(existing.size()==offsets.size()&&existing.stream().allMatch(e->offsets.contains(e.getKey())&&e.getValue().equals(when.minusSeconds(e.getKey()*60L))))return;s.db.update("DELETE FROM reminder WHERE owner_id=? AND "+col+"=?",owner,id);for(int offset:offsets){UUID rid=UUID.randomUUID();s.db.update("INSERT INTO reminder(id,owner_id,"+col+",offset_minutes,scheduled_at,idempotency_key) VALUES(?,?,?,?,?,?)",rid,owner,id,offset,utc(when.minusSeconds(offset*60L)),UUID.randomUUID());audit.care(owner,REMINDER_CREATED,"REMINDER",rid,false);}}
 void cancel(UUID owner,UUID id,boolean appointment){s.db.update("UPDATE reminder SET status='CANCELLED',version=version+1 WHERE owner_id=? AND "+(appointment?"appointment_id":"follow_up_id")+"=? AND status='PENDING'",owner,id);}
 public List<UUID> due(){return s.db.query("SELECT id FROM reminder WHERE status='PENDING' AND scheduled_at<=? ORDER BY scheduled_at,id LIMIT 100",(r,n)->r.getObject(1,UUID.class),utc(s.clock.instant()));}
 public void deliver(UUID id){var rows=s.db.query("SELECT owner_id,appointment_id,follow_up_id FROM reminder WHERE id=?",(r,n)->new UUID[]{r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class)},id);if(rows.isEmpty())return;var row=rows.getFirst();boolean ap=row[1]!=null;UUID source=ap?row[1]:row[2];String table=ap?"appointment":"follow_up";
  if(s.db.query("SELECT id FROM "+table+" WHERE id=? AND owner_id=? FOR UPDATE",(r,n)->r.getObject(1),source,row[0]).isEmpty())return;
  if(s.db.query("SELECT id FROM reminder WHERE id=? AND status='PENDING' AND scheduled_at<=? FOR UPDATE",(r,n)->r.getObject(1),id,utc(s.clock.instant())).isEmpty())return;
  String status=s.db.queryForObject("SELECT status FROM "+table+" WHERE id=? AND owner_id=?",String.class,source,row[0]);if(ap?!"SCHEDULED".equals(status):!Set.of("CONFIRMED","EDITED").contains(status)){cancel(row[0],source,ap);return;}
  s.db.update("INSERT INTO notification(id,owner_id,reminder_id,kind,title,body) VALUES(?,?,?,?,?,?)",UUID.randomUUID(),row[0],id,ap?"APPOINTMENT":"FOLLOW_UP",ap?"Appointment reminder":"Follow-up reminder","Open CarePath to review your scheduled item.");
  s.db.update("UPDATE reminder SET status='DELIVERED',delivered_at=?,version=version+1 WHERE id=?",utc(s.clock.instant()),id);audit.care(row[0],REMINDER_TRIGGERED,"REMINDER",id,true);
 }
 public Page<Reminder> list(int page,String status){if(!Set.of("ALL","PENDING").contains(status))throw invalid();String condition=status.equals("PENDING")?" AND status='PENDING'":"";return new Page<>(s.db.query("SELECT * FROM reminder WHERE owner_id=?"+condition+" ORDER BY scheduled_at,id LIMIT 20 OFFSET ?",(r,n)->new Reminder(r.getObject("id",UUID.class),r.getObject("appointment_id")==null?"FOLLOW_UP":"APPOINTMENT",r.getObject(r.getObject("appointment_id")==null?"follow_up_id":"appointment_id",UUID.class),time(r,"scheduled_at"),r.getInt("offset_minutes"),r.getString("status"),time(r,"delivered_at")),s.owner(),page*20L),s.db.queryForObject("SELECT count(*) FROM reminder WHERE owner_id=?"+condition,Long.class,s.owner()),page,20);}
 public Page<Notice> notifications(int page){return new Page<>(s.db.query("SELECT n.*,r.appointment_id,r.follow_up_id FROM notification n JOIN reminder r ON r.id=n.reminder_id AND r.owner_id=n.owner_id WHERE n.owner_id=? ORDER BY n.created_at DESC,n.id LIMIT 20 OFFSET ?",(r,n)->new Notice(r.getObject("id",UUID.class),r.getString("title"),r.getString("body"),time(r,"created_at"),time(r,"read_at"),r.getString("kind"),r.getObject(r.getObject("appointment_id")==null?"follow_up_id":"appointment_id",UUID.class)),s.owner(),page*20L),s.db.queryForObject("SELECT count(*) FROM notification WHERE owner_id=?",Long.class,s.owner()),page,20);}
 public long unread(){return s.db.queryForObject("SELECT count(*) FROM notification WHERE owner_id=? AND read_at IS NULL",Long.class,s.owner());}
 public void read(UUID id){if(id!=null)s.own("notification",id,s.owner());s.db.update("UPDATE notification SET read_at=? WHERE owner_id=? AND read_at IS NULL"+(id==null?"":" AND id=?"),id==null?new Object[]{utc(s.clock.instant()),s.owner()}:new Object[]{utc(s.clock.instant()),s.owner(),id});}
}
