package com.carepath.care;
import static com.carepath.care.CareDtos.*;import static com.carepath.care.CareSupport.*;import static com.carepath.audit.AuditService.Action.*;
import java.util.*;import java.sql.*;import java.time.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import com.carepath.longitudinal.HistoryDtos.Page;import com.carepath.audit.AuditService;
@Service @Transactional
public class SymptomService {
 private final CareSupport s;private final AuditService audit;
 public SymptomService(CareSupport s,AuditService a){this.s=s;audit=a;}
 private Symptom map(ResultSet r,int n)throws SQLException{return new Symptom(r.getObject("id",UUID.class),r.getString("name"),time(r,"started_at"),time(r,"resolved_at"),r.getInt("severity"),r.getString("frequency"),r.getString("notes"),r.getObject("resolved_at")==null?"ACTIVE":"RESOLVED",time(r,"created_at"),time(r,"updated_at"),r.getLong("version"));}
 public Symptom get(UUID id){return s.db.query("SELECT * FROM symptom WHERE id=? AND owner_id=?",this::map,id,s.owner()).stream().findFirst().orElseThrow(CareSupport::missing);}
 public Page<Symptom> list(String status,String q,int page){if(!Set.of("ALL","ACTIVE","RESOLVED").contains(status))throw invalid();String where="owner_id=? AND lower(name) LIKE ? ESCAPE '!'"+(status.equals("ALL")?"":status.equals("ACTIVE")?" AND resolved_at IS NULL":" AND resolved_at IS NOT NULL");String like="%"+q.toLowerCase(Locale.ROOT).replace("!","!!").replace("%","!%").replace("_","!_")+"%";return new Page<>(s.db.query("SELECT * FROM symptom WHERE "+where+" ORDER BY started_at DESC,id LIMIT 20 OFFSET ?",this::map,s.owner(),like,page*20L),s.db.queryForObject("SELECT count(*) FROM symptom WHERE "+where,Long.class,s.owner(),like),page,20);}
 public Symptom save(UUID id,SymptomInput x){if(x.startedAt().isAfter(s.clock.instant())||x.resolvedAt()!=null&&(x.resolvedAt().isBefore(x.startedAt())||x.resolvedAt().isAfter(s.clock.instant())))throw invalid();UUID owner=s.owner();boolean create=id==null;if(create){id=UUID.randomUUID();s.db.update("INSERT INTO symptom(id,owner_id,name,start_date,started_at,resolved_date,resolved_at,severity,frequency,notes) VALUES(?,?,?,?,?,?,?,?,?,?)",id,owner,x.name().strip(),x.startedAt().atOffset(ZoneOffset.UTC).toLocalDate(),utc(x.startedAt()),x.resolvedAt()==null?null:x.resolvedAt().atOffset(ZoneOffset.UTC).toLocalDate(),utc(x.resolvedAt()),x.severity(),x.frequency().name(),x.notes());}else{get(id);if(s.db.update("UPDATE symptom SET name=?,start_date=?,started_at=?,resolved_date=?,resolved_at=?,severity=?,frequency=?,notes=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND owner_id=? AND version=?",x.name().strip(),x.startedAt().atOffset(ZoneOffset.UTC).toLocalDate(),utc(x.startedAt()),x.resolvedAt()==null?null:x.resolvedAt().atOffset(ZoneOffset.UTC).toLocalDate(),utc(x.resolvedAt()),x.severity(),x.frequency().name(),x.notes(),id,owner,x.version())!=1)throw conflict();}audit.care(owner,create?SYMPTOM_CREATED:x.resolvedAt()!=null?SYMPTOM_RESOLVED:SYMPTOM_UPDATED,"SYMPTOM",id,false);return get(id);}
 public void delete(UUID id){get(id);s.db.update("DELETE FROM symptom WHERE id=? AND owner_id=?",id,s.owner());audit.care(s.owner(),SYMPTOM_DELETED,"SYMPTOM",id,false);}
}
