"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { assistantClient, type Answer, type Config } from "@/lib/assistant-client";
import { historyClient, type Concept } from "@/lib/history-client";
import { EvidenceReading } from "@/components/history/evidence-reading";
import { QuestionDraft, SavedQuestions } from "./saved-questions";
export function RecordAssistant() {
 const [question, setQuestion] = useState(""); const [concept, setConcept] = useState(""); const [concepts, setConcepts] = useState<Concept[]>([]); const [config, setConfig] = useState<Config | null>(null); const [ai, setAi] = useState(false); const [answer, setAnswer] = useState<Answer | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [configError, setConfigError] = useState(""); const [revision, setRevision] = useState(0); const [load, setLoad] = useState(0);
 useEffect(() => { let active = true; Promise.all([assistantClient.config(), historyClient.concepts()]).then(([c, h]) => { if (active) { setConfig(c); setConcepts(h.items); setConfigError(""); } }).catch(() => { if (active) setConfigError("Record choices are unavailable. Reload to retry."); }); return () => { active = false; }; }, [load]);
 async function submit() { setBusy(true); setError(""); setAnswer(null); try { setAnswer(await assistantClient.ask({ question, conceptId: concept || undefined, useAi: ai })); } catch { setError("The record explanation could not be loaded. Check your connection and retry."); } finally { setBusy(false); } }
 return <><div className="max-w-3xl"><p className="text-xs font-medium uppercase tracking-widest text-primary">Records, explained with evidence</p><h1 className="mt-2 text-3xl font-semibold">Ask about your records</h1><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Understand verified measurements and numerical changes. CarePath does not diagnose, prescribe or replace your clinician.</p></div><div className="mt-8 grid gap-9 lg:grid-cols-[minmax(0,1fr)_18rem]"><section><form onSubmit={(e) => { e.preventDefault(); void submit(); }}><label className="text-sm font-medium">Your question<textarea value={question} onChange={(e) => setQuestion(e.target.value)} required maxLength={1000} className="mt-2 block min-h-32 w-full rounded-lg border border-border bg-white p-4" placeholder="How has my hemoglobin changed?" /></label><label className="mt-4 block text-sm">Optional measurement scope<select value={concept} onChange={(e) => setConcept(e.target.value)} className="mt-1 block w-full rounded-md border border-border bg-white p-2"><option value="">Identify from my question</option>{concepts.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{configError && <p role="alert" className="mt-3 text-sm text-red-900">{configError} <button type="button" className="underline" onClick={() => setLoad((n) => n + 1)}>Reload</button></p>}<label className="mt-4 flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={ai} disabled={!config?.providerAvailable} onChange={(e) => setAi(e.target.checked)} /><span>Use optional AI wording for this request. Selected verified facts will be sent to the configured provider.</span></label>{config && !config.providerAvailable && <p className="mt-2 text-xs text-muted-foreground">AI provider unavailable. Evidence-linked rule-based explanations still work.</p>}<Button className="mt-5" disabled={busy || !question.trim()}>{busy ? "Reading selected facts…" : "Explain records"}</Button></form>{error && <p role="alert" className="mt-4 text-red-900">{error}</p>}{busy && <div className="mt-6 h-40 rounded-lg bg-muted motion-safe:animate-pulse" role="status"><span className="sr-only">Preparing an evidence-grounded answer</span></div>}
 {answer && <article className="mt-8" aria-live="polite"><h2 className="text-xl font-semibold">{answer.mode === "URGENT" ? "Seek urgent professional help" : "Your record explanation"}</h2><p className="mt-3 text-sm">{answer.message}</p><p className="mt-3 rounded-md bg-muted p-3 text-sm">{answer.uncertainty}</p>{answer.providerStatus !== "AVAILABLE" && answer.providerStatus !== "NOT_REQUESTED" && answer.providerStatus !== "NOT_CALLED" && <p className="mt-3 text-sm text-muted-foreground">AI wording unavailable ({answer.providerStatus.toLowerCase().replaceAll("_", " ")}). The explanation below uses CarePath rules.</p>}{answer.explanation.length > 0 && <section className="mt-6 border-l-2 border-primary pl-4"><h3 className="text-xs font-semibold uppercase tracking-wide">{answer.mode === "AI_CONSTRAINED" ? "AI explanation · approved wording only" : "Deterministic explanation"}</h3>{answer.explanation.map((text, i) => <p key={i} className="mt-3 text-sm leading-relaxed">{text}</p>)}</section>}{answer.facts.length > 0 && <section className="mt-7"><h3 className="font-semibold">Verified record facts</h3><ul className="mt-3 space-y-4">{answer.facts.map((fact) => <li key={fact.id} className="border-b border-border pb-3 text-sm"><p>{fact.text}</p><div className="mt-2 flex flex-wrap gap-3">{fact.evidenceIds.map((id) => <a key={id} href={`#evidence-${id}`} className="text-primary underline">View evidence {id}</a>)}</div></li>)}</ul></section>}{answer.evidence.map((source) => <details key={source.id} id={`evidence-${source.id}`} className="mt-4 scroll-mt-6 rounded-lg border border-border p-4"><summary className="cursor-pointer text-sm font-medium">{source.id} · {source.observation.evidence.filename} · page {source.observation.evidence.page}</summary><div className="mt-4"><EvidenceReading point={source.observation} /></div></details>)}{answer.referenceUrls.length > 0 && <section className="mt-5"><h3 className="text-sm font-semibold">Reference information · predefined safety sources</h3>{answer.referenceUrls.filter((url) => url.startsWith("https://www.nhs.uk/") || url.startsWith("https://www.londonambulance.nhs.uk/")).map((url) => <a key={url} className="mt-2 block break-all text-xs text-primary underline" href={url} rel="noreferrer" target="_blank">{url}</a>)}</section>}{answer.suggestedQuestions.length > 0 && <section className="mt-8"><h3 className="font-semibold">Prepare for a clinical conversation</h3>{answer.suggestedQuestions.map((draft, i) => <QuestionDraft key={`${draft.text}-${i}`} draft={draft} onSaved={() => setRevision((n) => n + 1)} />)}</section>}</article>}
 </section><aside className="border-l border-border pl-5"><h2 className="text-sm font-semibold">Start with your evidence</h2><div className="mt-4 space-y-4">{["How has my hemoglobin changed?", "What changed between my latest reports?", "Explain my Vitamin D results in simple language.", "Where did the September hemoglobin result come from?"].map((text) => <button key={text} className="block text-left text-sm leading-relaxed text-primary underline" onClick={() => { setQuestion(text); setConcept(""); }}>{text}</button>)}</div><p className="mt-7 text-xs leading-relaxed text-muted-foreground">{config?.privacy ?? "Questions and answers are not retained. Only questions you explicitly save are stored."}</p><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Record facts, reference information and AI wording are labelled separately. Source snippets stay inside CarePath. Emergency phrase detection is limited and is not a triage service.</p></aside></div><SavedQuestions revision={revision} onChanged={() => setRevision((n) => n + 1)} /></>;
}
