"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { assistantClient, type Saved, type Suggestion } from "@/lib/assistant-client";
import { evidenceUrl, type Page } from "@/lib/history-client";
export function QuestionDraft({ draft, onSaved }: { draft: Suggestion; onSaved: () => void }) {
  const [text, setText] = useState(draft.text); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function save() { setBusy(true); setMessage(""); try { await assistantClient.save({ text, observationIds: draft.observationIds }); setMessage("Saved to your clinician questions."); onSaved(); } catch { setMessage("Could not save. Your source may have changed; reload the explanation before retrying."); } finally { setBusy(false); } }
  return <div className="my-3"><label className="text-sm">Editable clinician question<textarea className="mt-1 block min-h-24 w-full rounded-md border border-border p-3" value={text} onChange={(e) => setText(e.target.value)} maxLength={1000} /></label><Button className="mt-2" variant="outline" disabled={busy || !text.trim()} onClick={save}>{busy ? "Saving…" : "Save question"}</Button>{message && <p role="status" className="mt-2 text-sm">{message}</p>}</div>;
}
function SavedRow({ item, onChanged }: { item: Saved; onChanged: () => void }) {
  const [text, setText] = useState(item.text); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [confirm, setConfirm] = useState(false);
  async function mutate(remove: boolean) { setBusy(true); setError(""); try { if (remove) await assistantClient.delete(item.id); else await assistantClient.edit(item.id, text, item.version); onChanged(); } catch { setError("Could not confirm the change. Reload before retrying; your draft is still shown here."); } finally { setBusy(false); } }
  return <li className="border-b border-border py-5"><p className="mb-2 text-xs text-muted-foreground">Your saved draft · {new Date(item.updatedAt).toLocaleDateString()}</p><label className="text-sm">Question<textarea value={text} maxLength={1000} onChange={(e) => setText(e.target.value)} className="mt-1 block min-h-24 w-full rounded-md border border-border p-3" /></label><div className="mt-3 flex flex-wrap gap-3"><Button variant="outline" disabled={busy || !text.trim()} onClick={() => mutate(false)}>Save edits</Button><Button variant="outline" disabled={busy} onClick={() => setConfirm(true)}>Delete</Button></div>{confirm && <div className="mt-3 rounded-md border border-border p-3" role="group" aria-label="Confirm question deletion"><p className="text-sm">Delete this saved question?</p><Button className="mt-2" disabled={busy} onClick={() => mutate(true)}>Confirm delete</Button><button className="ml-4 text-sm underline" onClick={() => setConfirm(false)}>Cancel</button></div>}{error && <p role="alert" className="mt-2 text-red-900">{error}</p>}{item.evidenceMissing && <p className="mt-3 text-sm text-amber-900">Some linked evidence was deleted or is no longer verified. This draft may be outdated.</p>}<ul className="mt-3 space-y-1">{item.evidence.map((p) => <li key={p.id}><Link className="text-sm text-primary underline" href={evidenceUrl(p.evidence)}>View evidence: {p.evidence.filename} · page {p.evidence.page}</Link></li>)}</ul></li>;
}
export function SavedQuestions({ revision, onChanged }: { revision: number; onChanged: () => void }) {
  const [result, setResult] = useState<Page<Saved> | null>(null); const [page, setPage] = useState(0); const [error, setError] = useState("");
  useEffect(() => { let active = true; assistantClient.list(page).then((r) => { if (active) { setResult(r); setError(""); } }).catch(() => { if (active) setError("Saved questions unavailable. Reload to retry."); }); return () => { active = false; }; }, [page, revision]);
  return <section className="mt-12 border-t border-border pt-8" aria-label="Saved clinician questions"><h2 className="text-xl font-semibold">Questions for your clinician</h2><p className="mt-2 text-sm text-muted-foreground">Private, editable notes for a future visit. Your wording is not a verified clinical conclusion.</p><details className="my-4"><summary className="cursor-pointer text-primary">Write a question yourself</summary><QuestionDraft draft={{ text: "", observationIds: [] }} onSaved={onChanged} /></details>{error ? <p role="alert">{error} <button className="underline" onClick={onChanged}>Reload</button></p> : !result ? <p role="status">Loading saved questions…</p> : result.items.length === 0 ? <p className="py-5 text-sm text-muted-foreground">No questions on this page. Save a suggested question or write your own.</p> : <ul>{result.items.map((item) => <SavedRow key={`${item.id}-${item.version}`} item={item} onChanged={onChanged} />)}</ul>}<nav className="mt-4 flex items-center justify-between" aria-label="Question pages"><Button variant="outline" disabled={page === 0} onClick={() => setPage((n) => n - 1)}>Previous</Button><span className="text-sm">Page {page + 1}</span><Button variant="outline" disabled={!result || (page + 1) * 20 >= result.total} onClick={() => setPage((n) => n + 1)}>Next</Button></nav></section>;
}
