"use client";
import {SharePanel} from "@/components/sharing/share-panel";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { packs, packSections, type Pack, type PackInput, type PackPreview, type PackType, type Selection } from "@/lib/pack-client";
import { care } from "@/lib/care-client";
import { Button } from "@/components/ui/button";
import { fieldClass, ErrorNote, Loading } from "@/components/care/shared";
import { PackPicker } from "./pack-picker";
import { PackView } from "./pack-view";
const empty: PackInput={title:"Doctor Visit Pack",reasonForVisit:"",appointmentId:null,packDate:null,items:[],version:0};
export function PackBuilder({ packId }: { packId?: string }) {
 const router=useRouter();const [pack,setPack]=useState<Pack|null>(null);const [draft,setDraft]=useState<PackInput>(empty);const [preview,setPreview]=useState<PackPreview|null>(null);const [labels,setLabels]=useState<string[]>([]);const [appointmentLabel,setAppointmentLabel]=useState("");const [pickAppointment,setPickAppointment]=useState(false);const [kind,setKind]=useState<Exclude<PackType,"MANUAL_QUESTION">>("SYMPTOM");const [manual,setManual]=useState("");const [loading,setLoading]=useState(Boolean(packId));const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [retry,setRetry]=useState(0);const deletion=useRef<HTMLDialogElement>(null);
 useEffect(()=>{let active=true;
  async function load(){try {
   if(packId){const p=await packs.get(packId);if(!active)return;setPack(p);setDraft({title:p.title,reasonForVisit:p.reasonForVisit,appointmentId:p.appointmentId,packDate:p.packDate,items:p.selections,version:p.version});if(p.appointmentId)care.appointment(p.appointmentId).then(a=>{if(active)setAppointmentLabel(a.providerName);}).catch(()=>{if(active)setAppointmentLabel("Original appointment no longer available");});if(p.status==="DRAFT"){try{const v=await packs.preview(packId);if(active){setPreview(v);setLabels(v.content.items.slice(p.appointmentId?1:0).map(i=>i.heading));}}catch{if(active)setError("A selected source is missing or no longer trusted. Remove it before previewing.");}}}
   else {const id=new URLSearchParams(window.location.search).get("appointment");if(id){const a=await care.appointment(id);if(active){setDraft({...empty,appointmentId:a.id});setAppointmentLabel(a.providerName);}}}
  }catch(e){if(active)setError(e instanceof Error?e.message:"Pack unavailable.");}finally{if(active)setLoading(false);}}
  void load();return()=>{active=false;};
 },[packId,retry]);
 function change(next:PackInput){setDraft(next);setPreview(null);setMessage("");}
 function add(s:Selection,label:string){if(draft.items.length>=40){setError("Select at most 40 items.");return;}if(s.type!=="MANUAL_QUESTION"&&draft.items.some(x=>x.type===s.type&&x.sourceId===s.sourceId&&x.otherId===s.otherId)){setError("This item is already selected.");return;}change({...draft,items:[...draft.items,s]});setLabels([...labels,label]);setError("");}
 function move(index:number,direction:number){const items=[...draft.items],titles=[...labels];[items[index],items[index+direction]]=[items[index+direction],items[index]];[titles[index],titles[index+direction]]=[titles[index+direction],titles[index]];change({...draft,items});setLabels(titles);}
 async function save(){setBusy(true);setError("");try{const p=await packs.save(pack?.id??null,draft);setPack(p);setDraft({...draft,version:p.version});const v=await packs.preview(p.id);setPreview(v);setLabels(v.content.items.slice(p.appointmentId?1:0).map(i=>i.heading));setMessage("Draft saved. Review the preview before generation.");if(!packId)router.replace(`/visit-packs/${encodeURIComponent(p.id)}`);}catch(e){setError(e instanceof Error?e.message:"Save failed.");}finally{setBusy(false);}}
 async function generate(){if(!pack||!preview)return;setBusy(true);setError("");try{const p=await packs.generate(pack.id,draft.version,preview.hash);setPack(p);setMessage("Generated. This snapshot will not change when source records are edited.");}catch(e){setPreview(null);setError(e instanceof Error?e.message:"Generation failed.");}finally{setBusy(false);}}
 async function download(){if(!pack)return;setBusy(true);setError("");try{const blob=await packs.pdf(pack.id);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="carepath-visit-pack.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:"Download failed.");}finally{setBusy(false);}}
 async function revise(){if(!pack)return;setBusy(true);try{const next=await packs.revise(pack.id);router.push(`/visit-packs/${encodeURIComponent(next.id)}`);}catch(e){setError(e instanceof Error?e.message:"Revision failed.");}finally{setBusy(false);}}
 async function remove(){if(!pack)return;setBusy(true);try{await packs.remove(pack.id);router.push("/visit-packs");}catch(e){setError(e instanceof Error?e.message:"Deletion failed.");deletion.current?.close();setBusy(false);}}
 if(loading)return <Loading/>;
 if(packId&&!pack)return <><Link href="/visit-packs" className="text-primary underline">All Visit Packs</Link><ErrorNote message={error||"Pack unavailable."}/><Button onClick={()=>setRetry(x=>x+1)}>Retry</Button></>;
 return <><Link href="/visit-packs" className="text-sm text-primary underline">All Visit Packs</Link><div className="my-6 flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-primary">Visit preparation</p><h1 className="mt-2 text-2xl font-semibold">{pack?.status==="GENERATED"?"Your generated Visit Pack":"Build a focused Visit Pack"}</h1></div>{pack&&<Button variant="outline" disabled={busy} onClick={()=>deletion.current?.showModal()}>Delete pack</Button>}</div><ErrorNote message={error}/>{error&&<Button variant="outline" disabled={busy} onClick={()=>setRetry(x=>x+1)}>Reload saved pack</Button>}{message&&<p role="status" className="my-4 text-sm text-primary">{message}</p>}
 {pack?.status==="GENERATED"&&pack.snapshot?<><div className="mb-6 flex flex-wrap gap-3"><Button disabled={busy} onClick={download}>Download PDF</Button><Button variant="outline" disabled={busy} onClick={revise}>Create next draft revision</Button></div><SharePanel packId={pack.id}/><PackView content={pack.snapshot} prepared={pack.generatedAt}/></>:<>
 <form onSubmit={e=>{e.preventDefault();void save();}} className="space-y-8"><fieldset disabled={busy} className="space-y-8 disabled:opacity-70"><section className="border-y border-border py-6"><h2 className="text-lg font-semibold">1. Visit details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">Title<input className={fieldClass} required maxLength={160} value={draft.title} onChange={e=>change({...draft,title:e.target.value})}/></label><label className="text-sm">Optional visit context date<input type="date" className={fieldClass} value={draft.packDate??""} onChange={e=>change({...draft,packDate:e.target.value||null})}/></label><label className="text-sm sm:col-span-2">Reason for visit<textarea className={fieldClass} required maxLength={2000} rows={3} value={draft.reasonForVisit} onChange={e=>change({...draft,reasonForVisit:e.target.value})}/></label></div><div className="mt-4 flex flex-wrap items-center gap-3"><span className="text-sm">{draft.appointmentId?`Appointment: ${appointmentLabel||"Selected appointment"}`:"No appointment selected"}</span><Button type="button" variant="outline" size="sm" onClick={()=>setPickAppointment(!pickAppointment)}>Choose upcoming appointment</Button>{draft.appointmentId&&<Button type="button" variant="outline" size="sm" onClick={()=>{change({...draft,appointmentId:null});setAppointmentLabel("");}}>Remove</Button>}</div>{pickAppointment&&<PackPicker kind="APPOINTMENT" target add={(s,label)=>{change({...draft,appointmentId:s.sourceId});setAppointmentLabel(label);setPickAppointment(false);}}/>}</section>
 <section><h2 className="text-lg font-semibold">2. Select relevant information</h2><p className="mt-2 text-sm text-muted-foreground">Only verified observations enter the record summary. Symptoms and questions stay labelled as user-reported. Select no more than 40 items.</p><label className="mt-4 block text-sm">Browse<select className={fieldClass} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{(["SYMPTOM","OBSERVATION","CHANGE","DOCUMENT","APPOINTMENT","FOLLOW_UP","SAVED_QUESTION"] as const).map(k=><option key={k} value={k}>{packSections[k]}</option>)}</select></label><PackPicker key={kind} kind={kind} add={add}/><label className="mt-5 block text-sm">Or write a pack-only clinician question<textarea className={fieldClass} maxLength={1000} rows={2} value={manual} onChange={e=>setManual(e.target.value)}/></label><Button className="mt-2" type="button" variant="outline" disabled={!manual.trim()} onClick={()=>{add({type:"MANUAL_QUESTION",sourceId:null,questionText:manual.trim()},manual.trim());setManual("");}}>Add question</Button></section>
 <section className="border-t border-border pt-6"><h2 className="text-lg font-semibold">3. Review selections ({draft.items.length}/40)</h2>{!draft.items.length&&<p className="mt-3 text-sm text-muted-foreground">No items selected. A reason-only pack is allowed.</p>}<ol className="mt-3 divide-y divide-border">{draft.items.map((s,i)=><li className="py-4" key={`${s.type}-${s.sourceId}-${s.otherId}-${i}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-muted-foreground">{packSections[s.type]}</p><p className="mt-1 break-words text-sm font-medium">{labels[i]||s.questionText||"Selected source - inspect the preview"}</p>{s.type!=="MANUAL_QUESTION"&&!s.sourceId&&<p className="text-sm text-red-900">Source deleted. Remove this selection.</p>}</div><div className="flex gap-2"><Button type="button" variant="outline" size="sm" aria-label={`Move item ${i+1} up`} disabled={i===0} onClick={()=>move(i,-1)}>↑</Button><Button type="button" variant="outline" size="sm" aria-label={`Move item ${i+1} down`} disabled={i===draft.items.length-1} onClick={()=>move(i,1)}>↓</Button><Button type="button" variant="outline" size="sm" onClick={()=>{change({...draft,items:draft.items.filter((_,j)=>i!==j)});setLabels(labels.filter((_,j)=>i!==j));}}>Remove</Button></div></div>{["SYMPTOM","APPOINTMENT"].includes(s.type)&&<label className="mt-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={s.includeNotes??false} onChange={e=>change({...draft,items:draft.items.map((x,j)=>j===i?{...x,includeNotes:e.target.checked}:x)})}/>Include user notes</label>}{["SAVED_QUESTION","MANUAL_QUESTION"].includes(s.type)&&<label className="mt-3 block text-sm">{s.type==="SAVED_QUESTION"?"Optional pack-only wording (leave empty to keep saved question)":"Question wording"}<textarea className={fieldClass} maxLength={1000} value={s.questionText??""} onChange={e=>change({...draft,items:draft.items.map((x,j)=>j===i?{...x,questionText:e.target.value||null}:x)})}/></label>}</li>)}</ol><Button type="submit" className="mt-4">{busy?"Working…":"Save draft and preview"}</Button><p className="mt-2 text-xs text-muted-foreground">Selections stay private. Generation uses no LLM or external PDF service. Draft requests are limited to 8 KiB.</p></section></fieldset></form>
 {preview&&<section className="mt-10 border-t border-border pt-7"><div className="mb-5 flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">4. Preview and generate</h2><p className="mt-1 text-sm text-muted-foreground">Generation freezes this content. Later edits require a new revision.</p></div><Button disabled={busy} onClick={generate}>Generate immutable pack</Button></div><PackView content={preview.content}/></section>}</>}
 <dialog ref={deletion} className="m-auto max-w-md rounded-xl p-6 shadow-xl backdrop:bg-black/30"><h2 className="text-lg font-semibold">Delete this Visit Pack?</h2><p className="my-4 text-sm">This removes its draft and stored snapshot. Original records and other revisions remain. Downloaded copies cannot be recalled.</p><div className="flex gap-3"><Button variant="outline" disabled={busy} onClick={()=>deletion.current?.close()}>Keep pack</Button><Button disabled={busy} onClick={remove}>Delete pack</Button></div></dialog></>;
}
