"use client";
import Link from "next/link";
import { useState } from "react";
import { packs } from "@/lib/pack-client";
import { useCarePage, ErrorNote, Loading, Pages } from "@/components/care/shared";
export function PackList() {
 const [page,setPage]=useState(0);const result=useCarePage(()=>packs.list(page),[page]);
 return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-primary">Prepare for your visit</p><h1 className="mt-2 text-3xl font-semibold">Doctor Visit Packs</h1><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Choose the records and questions you want to discuss. Generated packs are private historical snapshots, with downloadable PDFs.</p></div><Link href="/visit-packs/new" className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-white">Prepare a pack</Link></div><ErrorNote message={result.error} />{result.error && <button className="underline" onClick={result.reload}>Retry</button>}{result.loading ? <Loading /> : result.data?.items.length ? <ul className="mt-8 divide-y divide-border border-y border-border">{result.data.items.map(p=><li key={p.id} className="flex flex-wrap items-center justify-between gap-3 py-5"><div className="min-w-0"><Link href={`/visit-packs/${encodeURIComponent(p.id)}`} className="break-words font-medium text-primary underline">{p.title}</Link><p className="mt-1 text-xs text-muted-foreground">{p.status} · Revision {p.revision} · {new Date(p.generatedAt ?? p.createdAt).toLocaleString()}</p></div><Link href={`/visit-packs/${encodeURIComponent(p.id)}`} className="text-sm underline">{p.status==="DRAFT"?"Continue draft":"View / download"}</Link></li>)}</ul>:!result.error&&<div className="my-10 border-y border-border py-10"><h2 className="font-medium">A focused conversation starts with selected records.</h2><p className="mt-2 text-sm text-muted-foreground">No packs yet. Nothing is included automatically.</p></div>}{result.data&&<Pages page={page} total={result.data.total} change={setPage}/>}</>;
}
