"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { care, localInput, offsetDate, type Appointment } from "@/lib/care-client";
import { Button } from "@/components/ui/button";
import { Field, Notes, OffsetFields, Pages, ErrorNote, Loading, fieldClass, useCarePage } from "./shared";
import { RecordPicker } from "./record-picker";
export function Appointments() {
 const [page, setPage] = useState(0); const [scope, setScope] = useState("UPCOMING"); const state = useCarePage(() => care.appointments(page, scope), [page, scope]); const [editing, setEditing] = useState<Appointment | null | undefined>(undefined); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<Appointment | null>(null);
 useEffect(() => { const id = new URLSearchParams(window.location.search).get("id"); if (id) care.appointment(id).then(setSelected).catch(() => state.setError("Selected appointment is unavailable.")); /* Initial deep link only. */
 // eslint-disable-next-line react-hooks/exhaustive-deps
 }, []);
 async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const text = (key: string) => String(f.get(key) ?? ""); setBusy(true); try { const result = await care.saveAppointment(editing?.id ?? null, { providerName: text("providerName"), specialty: text("specialty"), startsAt: offsetDate(text("startsAt")), timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone, location: text("location"), phone: text("phone"), externalUrl: text("externalUrl") || null, notes: text("notes"), followUpDate: text("followUpDate") || null, documentIds: f.getAll("documentIds").map(String), symptomIds: f.getAll("symptomIds").map(String), questionIds: f.getAll("questionIds").map(String), offsets: f.getAll("offsets").map(Number), version: editing?.version ?? 0 }); setSelected(result); setEditing(undefined); state.reload(); } catch (e) { state.setError(e instanceof Error ? e.message : "Could not save appointment."); } finally { setBusy(false); } }
 async function action(a: Appointment, kind: "COMPLETED" | "CANCELLED" | "DELETE") { if (!window.confirm(kind === "DELETE" ? "Delete this appointment and its reminders and notifications?" : `Mark appointment ${kind.toLowerCase()}? Pending reminders will stop.`)) return; setBusy(true); try { if (kind === "DELETE") { await care.deleteAppointment(a.id); setSelected(null); } else setSelected(await care.appointmentStatus(a.id, kind, a.version)); state.reload(); } catch (e) { state.setError(e instanceof Error ? e.message : "Action failed."); } finally { setBusy(false); } }
 const rows = selected ? [selected, ...(state.data?.items ?? []).filter((a) => a.id !== selected.id)] : state.data?.items ?? [];
 return <><p className="text-xs uppercase tracking-widest text-primary">Care schedule</p><div className="mt-2 flex flex-wrap justify-between gap-3"><h1 className="text-3xl font-semibold">Appointments</h1><Button onClick={() => setEditing(null)}>Add appointment</Button></div><p className="mt-3 text-sm text-muted-foreground">Organize visits and relevant records. Adding a visit here does not book it with a provider.</p><ErrorNote message={state.error} />{state.error && <Button variant="outline" onClick={state.reload}>Retry</Button>}
 {editing !== undefined && <form key={editing?.id ?? "new"} onSubmit={save} className="my-6 grid gap-4 rounded-xl border border-border p-5 md:grid-cols-2"><h2 className="font-semibold md:col-span-2">{editing ? "Edit appointment" : "New appointment"}</h2><Field label="Clinician / provider" name="providerName" required maxLength={255} defaultValue={editing?.providerName} /><Field label="Specialty" name="specialty" maxLength={160} defaultValue={editing?.specialty ?? ""} /><Field label="Date and time (your device timezone)" name="startsAt" type="datetime-local" required defaultValue={editing ? localInput(editing.startsAt) : undefined} /><p className="self-end text-sm text-muted-foreground">Saved with your device’s IANA timezone. The appointment displays its saved zone.</p><Field label="Location" name="location" maxLength={500} defaultValue={editing?.location ?? ""} /><Field label="Phone" name="phone" type="tel" maxLength={40} defaultValue={editing?.phone ?? ""} /><Field label="Official / external URL (HTTPS only)" name="externalUrl" type="url" maxLength={500} defaultValue={editing?.externalUrl ?? ""} /><Field label="Follow-up date (optional note)" name="followUpDate" type="date" defaultValue={editing?.followUpDate ?? ""} /><Notes value={editing?.notes} /><OffsetFields values={editing?.offsets} /><RecordPicker kind="document" selected={editing?.documentIds ?? []} /><RecordPicker kind="symptom" selected={editing?.symptomIds ?? []} /><RecordPicker kind="question" selected={editing?.questionIds ?? []} /><div className="flex gap-3 md:col-span-2"><Button disabled={busy}>Save appointment</Button><Button type="button" variant="outline" onClick={() => setEditing(undefined)}>Cancel</Button></div></form>}
 <label className="my-6 block max-w-xs text-sm">Show<select className={fieldClass} value={scope} onChange={(e) => { setScope(e.target.value); setPage(0); setSelected(null); }}>{["UPCOMING", "PAST", "ALL"].map((v) => <option key={v}>{v}</option>)}</select></label>
 {state.loading ? <Loading /> : !rows.length ? <p className="rounded-lg border border-dashed p-6">No appointments in this view.</p> : <ul className="divide-y divide-border">{rows.map((a) => <li className="py-5" key={a.id}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{a.providerName}</h2><span className="text-xs">{a.status}</span></div><p className="mt-2 text-sm">{new Date(a.startsAt).toLocaleString(undefined, { timeZone: a.timeZone })} · {a.timeZone}</p><p className="mt-1 text-sm text-muted-foreground">{a.specialty} · {a.location}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{a.notes}</p>{a.phone && <p className="mt-1 text-sm">Phone: {a.phone}</p>}{a.externalUrl?.startsWith("https://") && <a href={a.externalUrl} target="_blank" rel="noopener noreferrer" className="mt-2 block text-sm text-primary underline">External provider page</a>}<div className="mt-2 flex flex-wrap gap-3">{a.documentIds.map((id) => <Link key={id} className="text-xs text-primary underline" href={`/records/${encodeURIComponent(id)}`}>Linked report</Link>)}{a.symptomIds.length > 0 && <Link href="/symptoms" className="text-xs text-primary underline">Linked symptoms ({a.symptomIds.length})</Link>}{a.questionIds.length > 0 && <Link href="/assistant" className="text-xs text-primary underline">Linked questions ({a.questionIds.length})</Link>}</div><div className="mt-4 flex flex-wrap gap-3">{a.status === "SCHEDULED" && <><Button variant="outline" size="sm" onClick={() => setEditing(a)}>Edit</Button><Button variant="outline" size="sm" disabled={busy} onClick={() => action(a, "COMPLETED")}>Complete</Button><Button variant="outline" size="sm" disabled={busy} onClick={() => action(a, "CANCELLED")}>Cancel appointment</Button></>}<Button variant="outline" size="sm" disabled={busy} onClick={() => action(a, "DELETE")}>Delete</Button></div></li>)}</ul>}
 <Pages page={page} total={state.data?.total ?? 0} change={setPage} /></>;
}
