"use client";
import Link from "next/link";
import { care, sourceLink } from "@/lib/care-client";
import { vault } from "@/lib/vault-client";
import { assistantClient } from "@/lib/assistant-client";
import { useCarePage, ErrorNote, Loading } from "./shared";
import { Button } from "@/components/ui/button";
export function CareDashboard() {
 const appointments = useCarePage(() => care.appointments(0, "UPCOMING"), []);
 const changes = useCarePage(() => assistantClient.ask({ question: "What changed between my latest reports?", useAi: false }), []);
 const reminders = useCarePage(() => care.reminders(0, "PENDING"), []); const follow = useCarePage(() => care.followUps(0, "UPCOMING"), []); const docs = useCarePage(() => vault.list(new URLSearchParams({ page: "0", size: "5" })), []); const unread = useCarePage(care.unread, []);
 return <div className="mt-8 space-y-7"><section className="border-y border-border py-6"><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold">Upcoming appointment</h2><Link className="text-sm text-primary underline" href="/appointments">Manage appointments</Link></div><ErrorNote message={appointments.error} />{appointments.error && <Button onClick={appointments.reload}>Retry</Button>}{appointments.loading ? <Loading /> : appointments.data?.items[0] ? <div className="mt-4"><p className="text-xl font-medium">{appointments.data.items[0].providerName}</p><p className="mt-2 text-sm">{new Date(appointments.data.items[0].startsAt).toLocaleString(undefined, { timeZone: appointments.data.items[0].timeZone })} · {appointments.data.items[0].timeZone}</p><p className="mt-1 text-sm text-muted-foreground">{appointments.data.items[0].location}</p></div> : <p className="mt-3 text-sm text-muted-foreground">No upcoming appointment scheduled.</p>}</section>
 <section><h2 className="text-lg font-semibold">Recent health changes</h2><ErrorNote message={changes.error} />{changes.data?.facts.length ? <ul className="mt-3 space-y-2 text-sm">{changes.data.facts.slice(0, 3).map((f) => <li key={f.id}>{f.text}</li>)}</ul> : <p className="mt-3 text-sm text-muted-foreground">{changes.loading ? "Loading verified comparisons…" : "Not enough comparable verified reports yet."}</p>}<Link className="mt-3 inline-block text-sm text-primary underline" href="/changes">Compare reports and view evidence</Link></section>
 <section className="border-y border-border py-6"><h2 className="text-lg font-semibold">Reminders and follow-ups</h2><ErrorNote message={reminders.error || follow.error} /><ul className="mt-3 space-y-2 text-sm">{reminders.data?.items.filter((r) => r.status === "PENDING").slice(0, 5).map((r) => <li key={r.id}><Link href={sourceLink(r.sourceType, r.sourceId)} className="text-primary underline">{r.sourceType === "APPOINTMENT" ? "Appointment" : "Follow-up"}</Link> · {new Date(r.scheduledAt).toLocaleString()}</li>)}</ul><h3 className="mt-4 text-sm font-medium">Upcoming follow-ups</h3><ul className="mt-2 space-y-2 text-sm">{follow.data?.items.slice(0, 5).map((f) => <li key={f.id}><Link href={sourceLink("FOLLOW_UP", f.id)} className="text-primary underline">Follow-up · {f.confirmedDate}</Link></li>)}</ul>{follow.data?.total === 0 && <p className="mt-2 text-sm text-muted-foreground">No upcoming confirmed follow-ups.</p>}<Link href="/follow-ups" className="mt-2 inline-block text-sm text-primary underline">Review follow-ups</Link><p className="mt-3 text-sm"><Link href="/notifications" className="text-primary underline">{unread.data ? `${unread.data.count} unread notifications` : "Open notifications"}</Link></p></section>
 <section><h2 className="text-lg font-semibold">Recent documents</h2><ErrorNote message={docs.error} /><ul className="mt-3 divide-y divide-border">{docs.data?.items.map((d) => <li className="py-3 text-sm" key={d.id}><Link href={`/records/${encodeURIComponent(d.id)}`} className="text-primary underline">{d.originalFilename}</Link><span className="ml-3 text-xs text-muted-foreground">{d.status}</span></li>)}</ul>{!docs.loading && !docs.data?.items.length && <p className="mt-3 text-sm text-muted-foreground">No uploaded documents yet.</p>}</section><nav aria-label="Quick actions" className="flex flex-wrap gap-5 border-t border-border pt-6 text-sm text-primary underline"><Link href="/onboarding">Getting started</Link><Link href="/search">Search all records</Link><Link href="/records">Upload a report</Link><Link href="/symptoms">Record a symptom</Link><Link href="/appointments">Add appointment</Link><Link href="/assistant">Prepare questions</Link><Link href={appointments.data?.items[0] ? `/visit-packs/new?appointment=${encodeURIComponent(appointments.data.items[0].id)}` : "/visit-packs/new"}>Prepare Visit Pack</Link></nav></div>;
}
