"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { care, offsetDate, type FollowUp } from "@/lib/care-client";
import { Button } from "@/components/ui/button";
import { Field, OffsetFields, Pages, ErrorNote, Loading, useCarePage } from "./shared";
export function FollowUps() {
 const [page, setPage] = useState(0); const state = useCarePage(() => care.followUps(page), [page]); const [editing, setEditing] = useState<FollowUp | null>(null); const [selected, setSelected] = useState<FollowUp | null>(null); const [busy, setBusy] = useState(false);
 useEffect(() => { const id = new URLSearchParams(window.location.search).get("id"); if (id) care.followUp(id).then(setSelected).catch(() => state.setError("Selected follow-up is unavailable."));
 // eslint-disable-next-line react-hooks/exhaustive-deps
 }, []);
 async function decide(f: FollowUp, form?: FormData) { setBusy(true); try { const next = await care.decide(f.id, form ? "CONFIRM" : "IGNORE", f.version, form ? offsetDate(String(form.get("confirmedAt"))) : null, form ? Intl.DateTimeFormat().resolvedOptions().timeZone : null, form ? form.getAll("offsets").map(Number) : []); setSelected(next); setEditing(null); state.reload(); } catch (e) { state.setError(e instanceof Error ? e.message : "Decision could not be saved."); } finally { setBusy(false); } }
 const rows = selected ? [selected, ...(state.data?.items ?? []).filter((f) => f.id !== selected.id)] : state.data?.items ?? [];
 return <><p className="text-xs uppercase tracking-widest text-primary">Scheduling instructions</p><h1 className="mt-2 text-3xl font-semibold">Follow-ups</h1><p className="mt-3 max-w-2xl text-sm text-muted-foreground">Possible follow-ups from your documents. Check the source and choose a time before confirming. This does not book a clinical appointment.</p><ErrorNote message={state.error} />{state.error && <Button variant="outline" onClick={state.reload}>Retry</Button>}
 {editing && <form key={editing.id} className="my-6 grid gap-4 rounded-xl border border-border p-5 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); void decide(editing, new FormData(e.currentTarget)); }}><h2 className="font-semibold md:col-span-2">Review and confirm follow-up</h2><p className="text-sm md:col-span-2">Source suggestion: {editing.suggestedDate ?? "No reliable date — enter a date yourself."} Your chosen date is stored separately.</p><Field label="Confirmed date and time (device timezone)" type="datetime-local" name="confirmedAt" required /><OffsetFields /><div className="flex gap-3"><Button disabled={busy}>Confirm</Button><Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancel</Button></div></form>}
 {state.loading ? <Loading /> : !rows.length ? <p className="mt-6 rounded-lg border border-dashed p-6">No follow-up instructions detected. Process a document, or use its “Check follow-ups” action for an earlier extraction.</p> : <ul className="mt-6 divide-y divide-border">{rows.map((f) => <li key={f.id} className="py-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{f.status === "PENDING" ? "Possible follow-up detected" : `Follow-up · ${f.status.toLowerCase()}`}</h2><span className="text-xs text-muted-foreground">Parser confidence: {f.confidence}</span></div><blockquote className="my-3 border-l-2 border-primary pl-4 text-sm">{f.instruction}</blockquote><p className="text-sm">Suggested: {f.suggestedDate ?? "Insufficient date evidence"}</p>{f.confirmedAt && <p className="mt-1 text-sm">Confirmed: {new Date(f.confirmedAt).toLocaleString(undefined, { timeZone: f.timeZone ?? "UTC" })} · {f.timeZone}</p>}<Link className="mt-3 block text-sm text-primary underline" href={`/records/${encodeURIComponent(f.documentId)}?page=${f.page}`}>View source · {f.filename} · page {f.page}</Link>{f.status === "PENDING" && <div className="mt-4 flex flex-wrap gap-3"><Button size="sm" onClick={() => setEditing(f)}>Confirm / edit date</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => { if (window.confirm("Ignore this possible follow-up?")) void decide(f); }}>Ignore</Button></div>}</li>)}</ul>}<Pages page={page} total={state.data?.total ?? 0} change={setPage} /></>;
}
