"use client";
import { useEffect, useState } from "react";
import { care, localInput, type Symptom } from "@/lib/care-client";
import { Button } from "@/components/ui/button";
import { Field, Notes, Pages, ErrorNote, Loading, fieldClass, useCarePage } from "./shared";
export function Symptoms() {
 const [page, setPage] = useState(0); const [status, setStatus] = useState("ALL"); const [query, setQuery] = useState(""); const state = useCarePage(() => care.symptoms(page, status, query), [page, status, query]);
 const [selected, setSelected] = useState<Symptom | null>(null);
 useEffect(() => { let active = true; const id = new URLSearchParams(window.location.search).get("id"); if (id) care.symptom(id).then(s => { if (active) setSelected(s); }).catch(() => { if (active) state.setError("Selected symptom is unavailable."); }); return () => { active = false; };
 // eslint-disable-next-line react-hooks/exhaustive-deps
 }, []);
 const rows = selected ? [selected, ...(state.data?.items ?? []).filter(s => s.id !== selected.id)] : state.data?.items ?? [];
 const [editing, setEditing] = useState<Symptom | null | undefined>(undefined); const [busy, setBusy] = useState(false);
 async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); setBusy(true); try { const saved = await care.saveSymptom(editing?.id ?? null, { name: String(f.get("name")), startedAt: new Date(String(f.get("startedAt"))).toISOString(), resolvedAt: f.get("resolvedAt") ? new Date(String(f.get("resolvedAt"))).toISOString() : null, severity: Number(f.get("severity")), frequency: String(f.get("frequency")), notes: String(f.get("notes")), version: editing?.version ?? 0 }); setSelected(saved); setEditing(undefined); state.reload(); } catch (e) { state.setError(e instanceof Error ? e.message : "Could not save."); } finally { setBusy(false); } }
 async function change(s: Symptom, remove: boolean) { if (remove && !window.confirm("Delete this symptom? Its appointment links will also be removed.")) return; setBusy(true); try { if (remove) { await care.deleteSymptom(s.id); setSelected(null); } else setSelected(await care.saveSymptom(s.id, { ...s, resolvedAt: s.resolvedAt ? null : new Date().toISOString() })); state.reload(); } catch (e) { state.setError(e instanceof Error ? e.message : "Action failed."); } finally { setBusy(false); } }
 return <><p className="text-xs uppercase tracking-widest text-primary">User-reported history</p><div className="mt-2 flex items-center justify-between gap-4"><h1 className="text-3xl font-semibold">Symptoms</h1><Button onClick={() => setEditing(null)}>Record symptom</Button></div><p className="mt-3 text-sm text-muted-foreground">Your own observations, separate from verified laboratory readings. This is a record, not a diagnosis.</p><ErrorNote message={state.error} />{state.error && <Button variant="outline" onClick={state.reload}>Retry</Button>}
 {editing !== undefined && <form key={editing?.id ?? "new"} onSubmit={save} className="my-6 grid gap-4 rounded-xl border border-border p-5 md:grid-cols-2"><h2 className="font-semibold md:col-span-2">{editing ? "Edit symptom" : "New symptom"}</h2><Field label="Symptom" name="name" required maxLength={160} defaultValue={editing?.name} /><Field label="Started (your local time)" name="startedAt" type="datetime-local" required defaultValue={editing ? localInput(editing.startedAt) : undefined} /><Field label="Resolved (optional, local time)" name="resolvedAt" type="datetime-local" defaultValue={editing?.resolvedAt ? localInput(editing.resolvedAt) : undefined} /><Field label="Severity (1–10, self-reported)" name="severity" type="number" min={1} max={10} required defaultValue={editing?.severity ?? 1} /><label className="text-sm">Frequency<select name="frequency" className={fieldClass} defaultValue={editing?.frequency ?? "OCCASIONAL"}>{["ONCE", "OCCASIONAL", "DAILY", "CONSTANT"].map((v) => <option key={v}>{v}</option>)}</select></label><Notes value={editing?.notes} /><div className="flex gap-3"><Button disabled={busy}>Save symptom</Button><Button type="button" variant="outline" onClick={() => setEditing(undefined)}>Cancel</Button></div></form>}
 <div className="my-6 flex flex-wrap gap-4 border-y border-border py-4"><label className="text-sm">Status<select className={fieldClass} value={status} onChange={(e) => { setStatus(e.target.value); setPage(0); }}>{["ALL", "ACTIVE", "RESOLVED"].map((s) => <option key={s}>{s}</option>)}</select></label><label className="text-sm">Search<input className={fieldClass} maxLength={80} value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); }} /></label></div>
 {state.loading ? <Loading /> : rows.length ? <ul className="divide-y divide-border">{rows.map((s) => <li key={s.id} id={s.id} className="py-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{s.name}</h2><span className="text-xs text-muted-foreground">{s.status} · severity {s.severity}/10 · {s.frequency}</span></div><p className="mt-2 text-sm">Started {new Date(s.startedAt).toLocaleString()}{s.resolvedAt ? ` · Resolved ${new Date(s.resolvedAt).toLocaleString()}` : ""}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm text-muted-foreground">{s.notes}</p><div className="mt-3 flex flex-wrap gap-3"><Button size="sm" variant="outline" onClick={() => setEditing(s)}>Edit</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => change(s, false)}>{s.resolvedAt ? "Reopen" : "Mark resolved"}</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => change(s, true)}>Delete</Button></div></li>)}</ul> : <p className="rounded-lg border border-dashed p-6">No matching symptoms recorded.</p>}
 <Pages page={page} total={state.data?.total ?? 0} change={setPage} /></>;
}
