-- CarePath foundation. UUIDs are generated by the application or PostgreSQL.
-- No real or synthetic patient rows are seeded. Owner-scoped composite FKs prevent cross-owner links.
CREATE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = clock_timestamp(); RETURN NEW; END $$;


CREATE TABLE app_user (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
email varchar(254) NOT NULL CHECK (email = lower(email)),
password_hash varchar(255) NOT NULL,
display_name varchar(120) NOT NULL,
time_zone varchar(80) NOT NULL DEFAULT 'UTC',
locale varchar(20) NOT NULL DEFAULT 'en',
status varchar(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','DISABLED','DELETION_PENDING')),
onboarding_completed_at timestamptz,
last_login_at timestamptz,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (email)
);

CREATE TRIGGER app_user_updated BEFORE UPDATE ON app_user FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE refresh_token (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
family_id uuid NOT NULL,
parent_id uuid,
expires_at timestamptz NOT NULL,
revoked_at timestamptz,
used_at timestamptz,
device_label varchar(160),
CHECK (expires_at > created_at),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (parent_id, owner_id) REFERENCES refresh_token(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER refresh_token_updated BEFORE UPDATE ON refresh_token FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX refresh_token_owner_created_idx ON refresh_token (owner_id, created_at DESC);

CREATE INDEX refresh_token_family_idx ON refresh_token (owner_id, family_id);

CREATE TABLE medical_document (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
original_filename varchar(255) NOT NULL,
document_type varchar(32) NOT NULL DEFAULT 'OTHER' CHECK (document_type IN ('LAB_REPORT','PRESCRIPTION','DIAGNOSTIC_REPORT','DISCHARGE_SUMMARY','VACCINATION_RECORD','DOCTOR_NOTE','REFERRAL','MEDICAL_BILL','OTHER')),
document_date date,
date_precision varchar(12) CHECK (date_precision IN ('DAY','MONTH','YEAR','UNKNOWN')),
uploaded_at timestamptz NOT NULL DEFAULT now(),
provider_name varchar(255),
mime_type varchar(50) NOT NULL CHECK (mime_type IN ('application/pdf','image/jpeg','image/png')),
byte_size bigint NOT NULL CHECK (byte_size > 0 AND byte_size <= 20971520),
storage_key varchar(255) NOT NULL UNIQUE CHECK (storage_key ~ '^[a-zA-Z0-9_-]+$'),
storage_backend varchar(20) NOT NULL DEFAULT 'LOCAL' CHECK (storage_backend IN ('LOCAL','S3')),
sha256 char(64) NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
status varchar(20) NOT NULL DEFAULT 'UPLOADED' CHECK (status IN ('UPLOADED','PROCESSING','NEEDS_REVIEW','COMPLETED','FAILED')),
extraction_confidence numeric(5,4) CHECK (extraction_confidence BETWEEN 0 AND 1),
metadata jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(metadata) = 'object'),
tags text[] NOT NULL DEFAULT '{}',
error_code varchar(80),
processed_at timestamptz,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id)
);

CREATE TRIGGER medical_document_updated BEFORE UPDATE ON medical_document FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX medical_document_owner_created_idx ON medical_document (owner_id, created_at DESC);

CREATE INDEX medical_document_date_idx ON medical_document (owner_id, document_date DESC);

CREATE INDEX medical_document_filter_idx ON medical_document (owner_id, document_type, status);

CREATE INDEX medical_document_search_idx ON medical_document USING gin (to_tsvector('simple', coalesce(original_filename,'') || ' ' || coalesce(provider_name,'')));

CREATE TABLE document_extraction (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
document_id uuid NOT NULL,
revision integer NOT NULL CHECK (revision > 0),
pipeline_version varchar(60) NOT NULL,
extractor varchar(80) NOT NULL,
ocr_used boolean NOT NULL DEFAULT false,
classification varchar(32),
confidence numeric(5,4) CHECK (confidence BETWEEN 0 AND 1),
structured_result jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(structured_result) = 'object'),
completed_at timestamptz,
UNIQUE (document_id, revision),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER document_extraction_updated BEFORE UPDATE ON document_extraction FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX document_extraction_owner_created_idx ON document_extraction (owner_id, created_at DESC);

CREATE TABLE document_page (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
document_id uuid NOT NULL,
extraction_id uuid NOT NULL,
page_number integer NOT NULL CHECK (page_number > 0),
extracted_text text NOT NULL,
confidence numeric(5,4) CHECK (confidence BETWEEN 0 AND 1),
UNIQUE (extraction_id, page_number),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (extraction_id, owner_id) REFERENCES document_extraction(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER document_page_updated BEFORE UPDATE ON document_page FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX document_page_owner_created_idx ON document_page (owner_id, created_at DESC);

ALTER TABLE document_extraction ADD CONSTRAINT extraction_document_unique UNIQUE (id, document_id, owner_id);

ALTER TABLE document_page ADD CONSTRAINT page_extraction_document_fk FOREIGN KEY (extraction_id, document_id, owner_id) REFERENCES document_extraction(id, document_id, owner_id) ON DELETE CASCADE;

CREATE TABLE processing_job (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
document_id uuid NOT NULL,
job_type varchar(32) NOT NULL DEFAULT 'EXTRACT_DOCUMENT' CHECK (job_type IN ('EXTRACT_DOCUMENT','DELETE_BLOB')),
status varchar(16) NOT NULL DEFAULT 'QUEUED' CHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED')),
attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
max_attempts integer NOT NULL DEFAULT 3 CHECK (max_attempts BETWEEN 1 AND 10),
available_at timestamptz NOT NULL DEFAULT now(),
locked_until timestamptz,
locked_by varchar(120),
last_error_code varchar(80),
finished_at timestamptz,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER processing_job_updated BEFORE UPDATE ON processing_job FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX processing_job_owner_created_idx ON processing_job (owner_id, created_at DESC);

CREATE INDEX processing_job_due_idx ON processing_job (available_at) WHERE status IN ('QUEUED','RUNNING');

CREATE UNIQUE INDEX processing_job_active_idx ON processing_job(document_id, job_type) WHERE status IN ('QUEUED','RUNNING');

CREATE TABLE canonical_medical_concept (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
canonical_name varchar(160) NOT NULL UNIQUE,
identifier_system varchar(40),
identifier_code varchar(80),
specimen varchar(100),
method varchar(100),
property varchar(100),
canonical_unit varchar(50),
mapping_source text,
vocabulary_version varchar(80) NOT NULL,
CHECK ((identifier_system IS NULL) = (identifier_code IS NULL)),
CHECK (identifier_code IS NULL OR mapping_source IS NOT NULL),
UNIQUE (identifier_system, identifier_code),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TRIGGER canonical_medical_concept_updated BEFORE UPDATE ON canonical_medical_concept FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE concept_alias (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
concept_id uuid NOT NULL REFERENCES canonical_medical_concept(id) ON DELETE CASCADE,
normalized_alias varchar(160) NOT NULL,
context_key varchar(160) NOT NULL DEFAULT '',
mapping_confidence numeric(5,4) NOT NULL CHECK (mapping_confidence BETWEEN 0 AND 1),
reviewed boolean NOT NULL DEFAULT false,
source text NOT NULL,
UNIQUE (normalized_alias, context_key, concept_id),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TRIGGER concept_alias_updated BEFORE UPDATE ON concept_alias FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE unit_conversion_rule (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
concept_id uuid NOT NULL REFERENCES canonical_medical_concept(id) ON DELETE CASCADE,
source_unit varchar(50) NOT NULL,
target_unit varchar(50) NOT NULL,
multiplier numeric NOT NULL CHECK (multiplier > 0),
offset_value numeric NOT NULL DEFAULT 0,
rule_version varchar(60) NOT NULL,
source_citation text NOT NULL,
reviewed boolean NOT NULL DEFAULT false,
UNIQUE (concept_id, source_unit, target_unit, rule_version),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TRIGGER unit_conversion_rule_updated BEFORE UPDATE ON unit_conversion_rule FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE medical_observation (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
document_id uuid NOT NULL,
extraction_id uuid NOT NULL,
original_test_name varchar(255) NOT NULL,
original_value_text varchar(255) NOT NULL,
original_numeric_value numeric,
original_unit varchar(80),
original_reference_text varchar(255),
original_reference_low numeric,
original_reference_high numeric,
original_abnormal_flag varchar(30),
value_comparator varchar(4) CHECK (value_comparator IN ('=','<','<=','>','>=')),
concept_id uuid REFERENCES canonical_medical_concept(id),
canonical_name_snapshot varchar(160),
mapping_confidence numeric(5,4) CHECK (mapping_confidence BETWEEN 0 AND 1),
normalization_version varchar(60),
normalized_value numeric,
normalized_unit varchar(50),
normalized_reference_low numeric,
normalized_reference_high numeric,
conversion_rule_id uuid REFERENCES unit_conversion_rule(id),
observed_date date,
date_basis varchar(20) CHECK (date_basis IN ('SAMPLE','REPORT','USER_CONFIRMED','UNKNOWN')),
specimen varchar(100),
method varchar(100),
panel_key varchar(120),
laboratory varchar(255),
extraction_confidence numeric(5,4) CHECK (extraction_confidence BETWEEN 0 AND 1),
verification_status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (verification_status IN ('PENDING','AUTO_VERIFIED','CONFIRMED','CORRECTED','REJECTED')),
verified_at timestamptz,
CHECK (original_reference_low IS NULL OR original_reference_high IS NULL OR original_reference_low <= original_reference_high),
CHECK (normalized_reference_low IS NULL OR normalized_reference_high IS NULL OR normalized_reference_low <= normalized_reference_high),
CHECK ((normalized_value IS NULL) = (normalized_unit IS NULL)),
CHECK (normalized_value IS NULL OR concept_id IS NOT NULL),
CHECK (verification_status IN ('PENDING','REJECTED') OR verified_at IS NOT NULL),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (extraction_id, owner_id) REFERENCES document_extraction(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (extraction_id, document_id, owner_id) REFERENCES document_extraction(id, document_id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER medical_observation_updated BEFORE UPDATE ON medical_observation FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX medical_observation_owner_created_idx ON medical_observation (owner_id, created_at DESC);

CREATE INDEX medical_observation_history_idx ON medical_observation(owner_id, concept_id, observed_date DESC);

ALTER TABLE medical_observation ADD CONSTRAINT observation_extraction_unique UNIQUE (id, extraction_id, document_id, owner_id);

ALTER TABLE document_page ADD CONSTRAINT page_extraction_unique UNIQUE (id, extraction_id, document_id, owner_id);

CREATE TABLE observation_source (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
observation_id uuid NOT NULL,
page_id uuid NOT NULL,
extraction_id uuid NOT NULL,
document_id uuid NOT NULL,
evidence_text text NOT NULL CHECK (length(evidence_text) > 0),
char_start integer CHECK (char_start >= 0),
char_end integer,
bounding_box jsonb,
CHECK ((char_start IS NULL AND char_end IS NULL) OR (char_start IS NOT NULL AND char_end IS NOT NULL AND char_end > char_start)),
CHECK (bounding_box IS NULL OR jsonb_typeof(bounding_box) = 'object'),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (observation_id, extraction_id, document_id, owner_id) REFERENCES medical_observation(id, extraction_id, document_id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (page_id, extraction_id, document_id, owner_id) REFERENCES document_page(id, extraction_id, document_id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER observation_source_updated BEFORE UPDATE ON observation_source FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX observation_source_owner_created_idx ON observation_source (owner_id, created_at DESC);

CREATE TABLE observation_review (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
observation_id uuid NOT NULL,
action varchar(12) NOT NULL CHECK (action IN ('CONFIRM','CORRECT','REJECT')),
previous_value jsonb NOT NULL,
corrected_value jsonb,
reason text,
CHECK (action <> 'CORRECT' OR corrected_value IS NOT NULL),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (observation_id, owner_id) REFERENCES medical_observation(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER observation_review_updated BEFORE UPDATE ON observation_review FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX observation_review_owner_created_idx ON observation_review (owner_id, created_at DESC);

CREATE TABLE symptom (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
name varchar(160) NOT NULL,
start_date date NOT NULL,
severity smallint NOT NULL CHECK (severity BETWEEN 1 AND 10),
frequency varchar(160),
notes text,
resolved_date date,
CHECK (resolved_date IS NULL OR resolved_date >= start_date),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id)
);

CREATE TRIGGER symptom_updated BEFORE UPDATE ON symptom FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX symptom_owner_created_idx ON symptom (owner_id, created_at DESC);

CREATE TABLE appointment (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
provider_name varchar(255) NOT NULL,
specialty varchar(160),
starts_at timestamptz NOT NULL,
time_zone varchar(80) NOT NULL,
location text,
notes text,
status varchar(20) NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN ('SCHEDULED','COMPLETED','CANCELLED','MISSED')),
follow_up_date date,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id)
);

CREATE TRIGGER appointment_updated BEFORE UPDATE ON appointment FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX appointment_owner_created_idx ON appointment (owner_id, created_at DESC);

CREATE INDEX appointment_upcoming_idx ON appointment(owner_id, status, starts_at);

CREATE TABLE appointment_document (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
appointment_id uuid NOT NULL,
document_id uuid NOT NULL,
UNIQUE (appointment_id, document_id),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (appointment_id, owner_id) REFERENCES appointment(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER appointment_document_updated BEFORE UPDATE ON appointment_document FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX appointment_document_owner_created_idx ON appointment_document (owner_id, created_at DESC);

CREATE TABLE appointment_symptom (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
appointment_id uuid NOT NULL,
symptom_id uuid NOT NULL,
UNIQUE (appointment_id, symptom_id),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (appointment_id, owner_id) REFERENCES appointment(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (symptom_id, owner_id) REFERENCES symptom(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER appointment_symptom_updated BEFORE UPDATE ON appointment_symptom FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX appointment_symptom_owner_created_idx ON appointment_symptom (owner_id, created_at DESC);

CREATE TABLE clinical_visit (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
appointment_id uuid,
visited_on date NOT NULL,
clinician varchar(255),
specialty varchar(160),
reason text,
notes text,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (appointment_id, owner_id) REFERENCES appointment(id, owner_id) ON DELETE RESTRICT
);

CREATE TRIGGER clinical_visit_updated BEFORE UPDATE ON clinical_visit FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX clinical_visit_owner_created_idx ON clinical_visit (owner_id, created_at DESC);

CREATE TABLE prescription (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
document_id uuid NOT NULL,
issued_on date,
clinician varchar(255),
verbatim_instructions text,
verification_status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (verification_status IN ('PENDING','CONFIRMED','REJECTED')),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER prescription_updated BEFORE UPDATE ON prescription FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX prescription_owner_created_idx ON prescription (owner_id, created_at DESC);

CREATE TABLE prescription_item (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
prescription_id uuid NOT NULL,
medicine_name_as_written varchar(255) NOT NULL,
dose_as_written varchar(255),
frequency_as_written varchar(255),
duration_as_written varchar(255),
page_id uuid,
evidence_text text NOT NULL,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (prescription_id, owner_id) REFERENCES prescription(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (page_id, owner_id) REFERENCES document_page(id, owner_id) ON DELETE RESTRICT
);

CREATE TRIGGER prescription_item_updated BEFORE UPDATE ON prescription_item FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX prescription_item_owner_created_idx ON prescription_item (owner_id, created_at DESC);

CREATE TABLE follow_up (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
document_id uuid,
page_id uuid,
appointment_id uuid,
source_text text,
anchor_date date,
interval_value integer CHECK (interval_value > 0),
interval_unit varchar(12) CHECK (interval_unit IN ('DAY','WEEK','MONTH')),
suggested_date date,
confirmed_date date,
confidence numeric(5,4) CHECK (confidence BETWEEN 0 AND 1),
status varchar(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','CONFIRMED','EDITED','IGNORED','COMPLETED')),
CHECK (document_id IS NOT NULL OR appointment_id IS NOT NULL),
CHECK (status NOT IN ('CONFIRMED','EDITED','COMPLETED') OR confirmed_date IS NOT NULL),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (page_id, owner_id) REFERENCES document_page(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (appointment_id, owner_id) REFERENCES appointment(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER follow_up_updated BEFORE UPDATE ON follow_up FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX follow_up_owner_created_idx ON follow_up (owner_id, created_at DESC);

CREATE TABLE saved_question (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
question_text text NOT NULL CHECK (length(question_text) BETWEEN 1 AND 4000),
origin varchar(20) NOT NULL DEFAULT 'USER' CHECK (origin IN ('USER','RULE','AI_DRAFT')),
observation_id uuid,
status varchar(16) NOT NULL DEFAULT 'SAVED' CHECK (status IN ('DRAFT','SAVED','ARCHIVED')),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (observation_id, owner_id) REFERENCES medical_observation(id, owner_id) ON DELETE RESTRICT
);

CREATE TRIGGER saved_question_updated BEFORE UPDATE ON saved_question FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX saved_question_owner_created_idx ON saved_question (owner_id, created_at DESC);

CREATE TABLE reminder (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
appointment_id uuid,
follow_up_id uuid,
offset_minutes integer NOT NULL DEFAULT 1440 CHECK (offset_minutes >= 0),
scheduled_at timestamptz NOT NULL,
channel varchar(12) NOT NULL DEFAULT 'IN_APP' CHECK (channel IN ('IN_APP','EMAIL')),
status varchar(16) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','PROCESSING','DELIVERED','FAILED','CANCELLED')),
idempotency_key uuid NOT NULL UNIQUE,
attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
next_attempt_at timestamptz NOT NULL DEFAULT now(),
locked_until timestamptz,
delivered_at timestamptz,
CHECK (num_nonnulls(appointment_id, follow_up_id) = 1),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (appointment_id, owner_id) REFERENCES appointment(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (follow_up_id, owner_id) REFERENCES follow_up(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER reminder_updated BEFORE UPDATE ON reminder FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX reminder_owner_created_idx ON reminder (owner_id, created_at DESC);

CREATE INDEX reminder_due_idx ON reminder(scheduled_at, next_attempt_at) WHERE status IN ('PENDING','PROCESSING');

CREATE TABLE notification (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
reminder_id uuid,
kind varchar(40) NOT NULL,
title varchar(160) NOT NULL,
body text NOT NULL,
read_at timestamptz,
UNIQUE (reminder_id),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (reminder_id, owner_id) REFERENCES reminder(id, owner_id) ON DELETE RESTRICT
);

CREATE TRIGGER notification_updated BEFORE UPDATE ON notification FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX notification_owner_created_idx ON notification (owner_id, created_at DESC);

CREATE TABLE visit_pack (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
title varchar(160) NOT NULL,
reason_for_visit text NOT NULL,
appointment_id uuid,
status varchar(16) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','READY','INVALIDATED','FAILED')),
revision integer NOT NULL DEFAULT 1 CHECK (revision > 0),
pdf_storage_key varchar(255) UNIQUE CHECK (pdf_storage_key ~ '^[a-zA-Z0-9_-]+$'),
snapshot jsonb,
generated_at timestamptz,
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (appointment_id, owner_id) REFERENCES appointment(id, owner_id) ON DELETE RESTRICT
);

CREATE TRIGGER visit_pack_updated BEFORE UPDATE ON visit_pack FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX visit_pack_owner_created_idx ON visit_pack (owner_id, created_at DESC);

CREATE TABLE visit_pack_item (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
visit_pack_id uuid NOT NULL,
position integer NOT NULL CHECK (position >= 0),
document_id uuid,
observation_id uuid,
symptom_id uuid,
prescription_id uuid,
visit_id uuid,
question_id uuid,
appointment_id uuid,
follow_up_id uuid,
CHECK (num_nonnulls(document_id, observation_id, symptom_id, prescription_id, visit_id, question_id, appointment_id, follow_up_id) = 1),
UNIQUE (visit_pack_id, position),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (visit_pack_id, owner_id) REFERENCES visit_pack(id, owner_id) ON DELETE CASCADE,
FOREIGN KEY (document_id, owner_id) REFERENCES medical_document(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (observation_id, owner_id) REFERENCES medical_observation(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (symptom_id, owner_id) REFERENCES symptom(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (prescription_id, owner_id) REFERENCES prescription(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (visit_id, owner_id) REFERENCES clinical_visit(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (question_id, owner_id) REFERENCES saved_question(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (appointment_id, owner_id) REFERENCES appointment(id, owner_id) ON DELETE RESTRICT,
FOREIGN KEY (follow_up_id, owner_id) REFERENCES follow_up(id, owner_id) ON DELETE RESTRICT
);

CREATE TRIGGER visit_pack_item_updated BEFORE UPDATE ON visit_pack_item FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX visit_pack_item_owner_created_idx ON visit_pack_item (owner_id, created_at DESC);

CREATE TABLE share_token (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
visit_pack_id uuid NOT NULL,
pack_revision integer NOT NULL CHECK (pack_revision > 0),
token_hash char(64) NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
expires_at timestamptz NOT NULL,
revoked_at timestamptz,
last_accessed_at timestamptz,
access_count bigint NOT NULL DEFAULT 0 CHECK (access_count >= 0),
CHECK (expires_at > created_at),
CHECK (expires_at <= created_at + interval '24 hours'),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id),
FOREIGN KEY (visit_pack_id, owner_id) REFERENCES visit_pack(id, owner_id) ON DELETE CASCADE
);

CREATE TRIGGER share_token_updated BEFORE UPDATE ON share_token FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX share_token_owner_created_idx ON share_token (owner_id, created_at DESC);

CREATE INDEX share_token_expiry_idx ON share_token(expires_at) WHERE revoked_at IS NULL;

CREATE TABLE audit_event (
id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
owner_id uuid NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
action varchar(80) NOT NULL,
resource_type varchar(40),
resource_id uuid,
request_id uuid,
outcome varchar(12) NOT NULL CHECK (outcome IN ('SUCCESS','DENIED','FAILURE')),
actor_kind varchar(12) NOT NULL CHECK (actor_kind IN ('OWNER','SHARE','SYSTEM')),
-- No free-form payload: never put tokens, documents, questions, or health values in audit events.
occurred_at timestamptz NOT NULL DEFAULT now(),
created_at timestamptz NOT NULL DEFAULT now(),
updated_at timestamptz NOT NULL DEFAULT now(),
version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
UNIQUE (id, owner_id)
);

CREATE TRIGGER audit_event_updated BEFORE UPDATE ON audit_event FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX audit_event_owner_created_idx ON audit_event (owner_id, created_at DESC);

CREATE INDEX audit_event_history_idx ON audit_event(owner_id, occurred_at DESC);

CREATE INDEX symptom_timeline_idx ON symptom(owner_id, start_date DESC);

CREATE VIEW trusted_medical_observation AS
SELECT o.* FROM medical_observation o
WHERE o.verification_status IN ('AUTO_VERIFIED','CONFIRMED','CORRECTED')
AND EXISTS (SELECT 1 FROM observation_source s WHERE s.observation_id = o.id AND s.owner_id = o.owner_id);

