package com.carepath.care;
import com.carepath.identity.AuthTestSupport;import com.carepath.intelligence.ProcessingWorker;import com.fasterxml.jackson.databind.*;import java.util.*;import java.time.*;import java.nio.file.*;import java.util.concurrent.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.mock.web.MockMultipartFile;import org.springframework.test.web.servlet.*;import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import static org.junit.jupiter.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class CareIntegrationTest extends AuthTestSupport {
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired JdbcTemplate db;@Autowired TestClock clock;@Autowired TestLimits limits;@Autowired ReminderService reminders;@Autowired ProcessingWorker worker;
 String a,b;
 @BeforeEach void setup()throws Exception{clock.reset();limits.clear();db.update("DELETE FROM audit_event");db.update("DELETE FROM app_user");a=account("care-a");b=account("care-b");}
 String account(String name)throws Exception{var reg=Map.of("email",name+"@example.invalid","password","Synthetic password 123!","displayName","Synthetic");mvc.perform(post("/api/v1/auth/register").header("Origin","http://localhost:3000").header("X-CarePath-Client","web").contentType("application/json").content(json.writeValueAsString(reg))).andExpect(status().isCreated());return body(mvc.perform(post("/api/v1/auth/login").header("Origin","http://localhost:3000").header("X-CarePath-Client","web").contentType("application/json").content(json.writeValueAsString(Map.of("email",reg.get("email"),"password",reg.get("password"))))).andExpect(status().isOk())).path("accessToken").asText();}
 JsonNode body(ResultActions r)throws Exception{return json.readTree(r.andReturn().getResponse().getContentAsString());}
 ResultActions req(String token,String method,String path,Object data)throws Exception{MockHttpServletRequestBuilder r=switch(method){case "POST"->post(path);case "PUT"->put(path);case "DELETE"->delete(path);default->get(path);};r.header("Authorization","Bearer "+token);if(data!=null)r.contentType("application/json").content(json.writeValueAsString(data));return mvc.perform(r);}
 JsonNode read(String token,String path)throws Exception{return body(req(token,"GET","/api/v1/care/"+path,null).andExpect(status().isOk()));}
 Map<String,Object> symptom(){var m=new LinkedHashMap<String,Object>();m.put("name","Synthetic headache");m.put("startedAt",clock.instant().minusSeconds(3600).toString());m.put("resolvedAt",null);m.put("severity",3);m.put("frequency","OCCASIONAL");m.put("notes","SYNTHETIC DEMO DATA — NOT A REAL PATIENT");m.put("version",0);return m;}
 Map<String,Object> appointment(long seconds){var m=new LinkedHashMap<String,Object>();m.put("providerName","Synthetic Clinic");m.put("startsAt",clock.instant().plusSeconds(seconds).atOffset(ZoneOffset.UTC).toString());m.put("timeZone","UTC");m.put("notes","private synthetic notes");m.put("documentIds",List.of());m.put("symptomIds",List.of());m.put("questionIds",List.of());m.put("offsets",List.of(0,60));m.put("version",0);return m;}
 JsonNode create(String token,String kind,Object input)throws Exception{return body(req(token,"POST","/api/v1/care/"+kind,input).andExpect(status().isCreated()));}
 String upload(String token)throws Exception{return body(mvc.perform(multipart("/api/v1/documents").file(new MockMultipartFile("file","synthetic.pdf","application/pdf",Files.readAllBytes(Path.of("../sample-data/phase4/january-lab.pdf")))).file(new MockMultipartFile("metadata","","application/json","{\"documentType\":\"LAB_REPORT\",\"documentDate\":\"2026-09-01\",\"tags\":[]}".getBytes())).header("Authorization","Bearer "+token)).andExpect(status().isCreated())).path("id").asText();}
 String candidate(String token,String instruction)throws Exception{String doc;try(var pdf=new org.apache.pdfbox.pdmodel.PDDocument();var out=new java.io.ByteArrayOutputStream()){var page=new org.apache.pdfbox.pdmodel.PDPage();pdf.addPage(page);try(var content=new org.apache.pdfbox.pdmodel.PDPageContentStream(pdf,page)){content.beginText();content.setFont(new org.apache.pdfbox.pdmodel.font.PDType1Font(org.apache.pdfbox.pdmodel.font.Standard14Fonts.FontName.HELVETICA),12);content.newLineAtOffset(50,700);content.showText("SYNTHETIC DEMO DATA - NOT A REAL PATIENT");content.newLineAtOffset(0,-30);content.showText(instruction);content.endText();}pdf.save(out);doc=body(mvc.perform(multipart("/api/v1/documents").file(new MockMultipartFile("file","synthetic-followup.pdf","application/pdf",out.toByteArray())).file(new MockMultipartFile("metadata","","application/json","{\"documentType\":\"DOCTOR_NOTE\",\"documentDate\":\"2026-09-01\",\"tags\":[]}".getBytes())).header("Authorization","Bearer "+token)).andExpect(status().isCreated())).path("id").asText();}req(token,"POST","/api/v1/documents/"+doc+"/process",null).andExpect(status().isAccepted());assertTrue(worker.runOne());req(token,"POST","/api/v1/care/documents/"+doc+"/detect-follow-ups",null).andExpect(status().isNoContent());return read(token,"follow-ups").path("items").get(0).path("id").asText();}
 Map<String,Object> decision(String action){var m=new LinkedHashMap<String,Object>();m.put("action",action);m.put("version",0);m.put("confirmedAt",clock.instant().minusSeconds(1).atOffset(ZoneOffset.UTC).toString());m.put("timeZone","UTC");m.put("offsets",List.of(0));return m;}
 @Test void symptomLifecycleAndTimeline()throws Exception{var input=symptom();var s=create(a,"symptoms",input);String id=s.path("id").asText();assertEquals("ACTIVE",s.path("status").asText());assertEquals(1,read(a,"symptoms").path("total").asInt());String events=req(a,"GET","/api/v1/history/events",null).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();assertTrue(events.contains("SYMPTOM"));assertTrue(events.contains(id));input.put("resolvedAt",clock.instant().toString());var resolved=body(req(a,"PUT","/api/v1/care/symptoms/"+id,input).andExpect(status().isOk()));assertEquals("RESOLVED",resolved.path("status").asText());input.put("version",1);input.put("resolvedAt",null);req(a,"PUT","/api/v1/care/symptoms/"+id,input).andExpect(status().isOk());assertEquals(1,read(a,"symptoms?status=ACTIVE&q=head").path("total").asInt());req(a,"DELETE","/api/v1/care/symptoms/"+id,null).andExpect(status().isNoContent());req(a,"GET","/api/v1/care/symptoms/"+id,null).andExpect(status().isNotFound());}
 @Test void symptomsNeverBecomeVerifiedMeasurements()throws Exception{create(a,"symptoms",symptom());assertEquals(0,body(req(a,"GET","/api/v1/history/concepts",null).andExpect(status().isOk())).path("total").asInt());var answer=body(req(a,"POST","/api/v1/assistant/ask",Map.of("question","How has my hemoglobin changed?","useAi",false)).andExpect(status().isOk()));assertEquals(0,answer.path("facts").size());assertFalse(answer.toString().contains("headache"));}
 @Test void invalidSymptomFieldsAndStaleVersion()throws Exception{for(var pair:List.of(Map.entry("severity",(Object)11),Map.entry("frequency",(Object)"INVALID"),Map.entry("startedAt",(Object)clock.instant().plusSeconds(5).toString()),Map.entry("resolvedAt",(Object)clock.instant().minusSeconds(7200).toString()))){var x=symptom();x.put(pair.getKey(),pair.getValue());req(a,"POST","/api/v1/care/symptoms",x).andExpect(status().isBadRequest());}var x=symptom();String id=create(a,"symptoms",x).path("id").asText();req(a,"PUT","/api/v1/care/symptoms/"+id,x).andExpect(status().isOk());req(a,"PUT","/api/v1/care/symptoms/"+id,x).andExpect(status().isConflict());}
 @Test void appointmentLifecycleReschedulesAndCancels()throws Exception{var x=appointment(7200);var ap=create(a,"appointments",x);String id=ap.path("id").asText();assertEquals(2,read(a,"reminders").path("total").asInt());x.put("version",ap.path("version").asLong());x.put("startsAt",clock.instant().plusSeconds(10800).atOffset(ZoneOffset.UTC).toString());var updated=body(req(a,"PUT","/api/v1/care/appointments/"+id,x).andExpect(status().isOk()));req(a,"PUT","/api/v1/care/appointments/"+id,x).andExpect(status().isConflict());req(a,"POST","/api/v1/care/appointments/"+id+"/status",Map.of("status","CANCELLED","version",updated.path("version").asLong())).andExpect(status().isOk());assertTrue(read(a,"reminders").path("items").get(0).path("status").asText().equals("CANCELLED"));assertEquals(0,read(a,"appointments?scope=UPCOMING").path("total").asInt());req(a,"DELETE","/api/v1/care/appointments/"+id,null).andExpect(status().isNoContent());assertEquals(0,read(a,"reminders").path("total").asInt());}
 @Test void appointmentOrderingPastAndTimezone()throws Exception{create(a,"appointments",appointment(7200));var early=create(a,"appointments",appointment(3600));create(a,"appointments",appointment(-3600));assertEquals(early.path("id"),read(a,"appointments?scope=UPCOMING").path("items").get(0).path("id"));assertEquals(1,read(a,"appointments?scope=PAST").path("total").asInt());var x=appointment(1000);x.put("startsAt","2027-01-01T10:00:00+05:30");x.put("timeZone","Asia/Kolkata");assertEquals("2027-01-01T04:30:00Z",create(a,"appointments",x).path("startsAt").asText());x.put("startsAt","2027-01-01T10:00:00Z");req(a,"POST","/api/v1/care/appointments",x).andExpect(status().isBadRequest());}
 @Test void completionIsIdempotentAndStopsPendingReminders()throws Exception{var ap=create(a,"appointments",appointment(3600));var action=Map.of("status","COMPLETED","version",ap.path("version").asLong());String path="/api/v1/care/appointments/"+ap.path("id").asText()+"/status";req(a,"POST",path,action).andExpect(status().isOk());req(a,"POST",path,action).andExpect(status().isOk());assertEquals(1,db.queryForObject("SELECT count(*) FROM audit_event WHERE action='APPOINTMENT_COMPLETED'",Integer.class));assertTrue(reminders.due().isEmpty());}
 @Test void unsupportedUrlsAndOffsetsRejected()throws Exception{var x=appointment(3600);x.put("externalUrl","javascript:alert(1)");req(a,"POST","/api/v1/care/appointments",x).andExpect(status().isBadRequest());x.remove("externalUrl");x.put("offsets",List.of(-1));req(a,"POST","/api/v1/care/appointments",x).andExpect(status().isBadRequest());x.put("offsets",List.of(0));x.put("timeZone","Mars/Nowhere");req(a,"POST","/api/v1/care/appointments",x).andExpect(status().isBadRequest());}
 @Test void bidirectionalSymptomAppointmentIdor()throws Exception{for(String[] pair:List.of(new String[]{a,b},new String[]{b,a})){String owner=pair[0],other=pair[1];String sid=create(owner,"symptoms",symptom()).path("id").asText();String aid=create(owner,"appointments",appointment(3600)).path("id").asText();for(String path:List.of("symptoms/"+sid,"appointments/"+aid)){req(other,"GET","/api/v1/care/"+path,null).andExpect(status().isNotFound());req(other,"DELETE","/api/v1/care/"+path,null).andExpect(status().isNotFound());}req(other,"PUT","/api/v1/care/symptoms/"+sid,symptom()).andExpect(status().isNotFound());req(other,"PUT","/api/v1/care/appointments/"+aid,appointment(3600)).andExpect(status().isNotFound());req(other,"POST","/api/v1/care/appointments/"+aid+"/status",Map.of("status","CANCELLED","version",1)).andExpect(status().isNotFound());assertFalse(read(other,"symptoms").toString().contains(sid));assertFalse(read(other,"appointments").toString().contains(aid));}}
 @Test void linkedResourceOwnershipAndRollback()throws Exception{String doc=upload(b),sym=create(b,"symptoms",symptom()).path("id").asText();String question=body(req(b,"POST","/api/v1/assistant/questions",Map.of("text","Synthetic question","observationIds",List.of())).andExpect(status().isCreated())).path("id").asText();for(var link:List.of(Map.entry("documentIds",doc),Map.entry("symptomIds",sym),Map.entry("questionIds",question))){var x=appointment(3600);x.put(link.getKey(),List.of(link.getValue()));req(a,"POST","/api/v1/care/appointments",x).andExpect(status().isNotFound());}assertEquals(0,read(a,"appointments").path("total").asInt());var own=appointment(3600);own.put("documentIds",List.of(doc));own.put("symptomIds",List.of(sym));own.put("questionIds",List.of(question));assertEquals(1,create(b,"appointments",own).path("documentIds").size());}
 @Test void massAssignmentAndUnauthenticatedRoutes()throws Exception{for(String key:List.of("owner","userId","deliveredAt","status","createdBy")){var x=symptom();x.put(key,"forged");req(a,"POST","/api/v1/care/symptoms",x).andExpect(status().isBadRequest());}for(String path:List.of("symptoms","appointments","follow-ups","reminders","notifications"))mvc.perform(get("/api/v1/care/"+path)).andExpect(status().isUnauthorized());}
 @Test void futureDueDeliveryReadAndDeletion()throws Exception{var future=create(a,"appointments",appointment(7200));assertTrue(reminders.due().isEmpty());var ap=create(a,"appointments",appointment(-10));for(UUID id:reminders.due()){reminders.deliver(id);reminders.deliver(id);}assertEquals(2,read(a,"notifications/unread").path("count").asInt());var notices=read(a,"notifications").path("items");String nid=notices.get(0).path("id").asText();assertEquals(ap.path("id"),notices.get(0).path("sourceId"));req(b,"POST","/api/v1/care/notifications/"+nid+"/read",null).andExpect(status().isNotFound());assertEquals(0,read(b,"notifications").path("total").asInt());assertEquals(0,read(b,"reminders").path("total").asInt());req(a,"POST","/api/v1/care/notifications/"+nid+"/read",null).andExpect(status().isNoContent());req(a,"POST","/api/v1/care/notifications/"+nid+"/read",null).andExpect(status().isNoContent());assertEquals(1,read(a,"notifications/unread").path("count").asInt());req(a,"POST","/api/v1/care/notifications/read-all",null).andExpect(status().isNoContent());assertEquals(0,read(a,"notifications/unread").path("count").asInt());req(a,"DELETE","/api/v1/care/appointments/"+ap.path("id").asText(),null).andExpect(status().isNoContent());assertEquals(0,read(a,"notifications").path("total").asInt());assertEquals(2,read(a,"reminders").path("total").asInt());assertNotNull(future);}
 @Test void concurrentSchedulerExactlyOneNotification()throws Exception{var x=appointment(-1);x.put("offsets",List.of(0));create(a,"appointments",x);UUID id=reminders.due().getFirst();var pool=Executors.newFixedThreadPool(2);try{var start=new CountDownLatch(1);var one=pool.submit(()->{start.await();reminders.deliver(id);return true;});var two=pool.submit(()->{start.await();reminders.deliver(id);return true;});start.countDown();one.get();two.get();}finally{pool.shutdownNow();}assertEquals(1,read(a,"notifications").path("total").asInt());assertEquals(1,db.queryForObject("SELECT count(*) FROM audit_event WHERE action='REMINDER_TRIGGERED'",Integer.class));}
 @Test void metadataEditDoesNotRedeliver()throws Exception{var x=appointment(-1);x.put("offsets",List.of(0));var ap=create(a,"appointments",x);reminders.deliver(reminders.due().getFirst());x.put("version",ap.path("version").asLong());x.put("notes","Edited notes");req(a,"PUT","/api/v1/care/appointments/"+ap.path("id").asText(),x).andExpect(status().isOk());assertTrue(reminders.due().isEmpty());assertEquals(1,read(a,"notifications").path("total").asInt());}
 @Test void followupProvenanceEditedConfirmationAndReminder()throws Exception{String id=candidate(a,"Review after 6 weeks");var original=read(a,"follow-ups/"+id);assertEquals("2026-10-13",original.path("suggestedDate").asText());assertEquals("Review after 6 weeks",original.path("instruction").asText());assertEquals(1,original.path("page").asInt());String doc=original.path("documentId").asText();req(a,"POST","/api/v1/care/follow-ups/"+id+"/decision",decision("CONFIRM")).andExpect(status().isOk());var confirmed=read(a,"follow-ups/"+id);assertEquals("2026-10-13",confirmed.path("suggestedDate").asText());assertEquals("EDITED",confirmed.path("status").asText());assertEquals(original.path("instruction"),confirmed.path("instruction"));reminders.deliver(reminders.due().getFirst());assertEquals("FOLLOW_UP",read(a,"notifications").path("items").get(0).path("sourceType").asText());req(a,"POST","/api/v1/care/follow-ups/"+id+"/decision",decision("CONFIRM")).andExpect(status().isConflict());req(a,"DELETE","/api/v1/documents/"+doc,null).andExpect(status().isNoContent());assertEquals(0,read(a,"follow-ups").path("total").asInt());assertEquals(0,read(a,"notifications").path("total").asInt());}
 @Test void ignoreAndRedetectionIdempotent()throws Exception{String id=candidate(a,"Next visit in 2 weeks");var f=read(a,"follow-ups/"+id);req(a,"POST","/api/v1/care/follow-ups/"+id+"/decision",decision("IGNORE")).andExpect(status().isOk());req(a,"POST","/api/v1/care/documents/"+f.path("documentId").asText()+"/detect-follow-ups",null).andExpect(status().isNoContent());assertEquals(1,read(a,"follow-ups").path("total").asInt());assertEquals("IGNORED",read(a,"follow-ups/"+id).path("status").asText());assertEquals(0,read(a,"reminders").path("total").asInt());}
 @Test void followupIdorAndNoSchedulingBeforeConfirmation()throws Exception{for(String[] pair:List.of(new String[]{a,b},new String[]{b,a})){String id=candidate(pair[0],"Return after 14 days"),doc=read(pair[0],"follow-ups/"+id).path("documentId").asText();req(pair[1],"GET","/api/v1/care/follow-ups/"+id,null).andExpect(status().isNotFound());req(pair[1],"POST","/api/v1/care/follow-ups/"+id+"/decision",decision("CONFIRM")).andExpect(status().isNotFound());req(pair[1],"POST","/api/v1/care/follow-ups/"+id+"/decision",decision("IGNORE")).andExpect(status().isNotFound());req(pair[1],"POST","/api/v1/care/documents/"+doc+"/detect-follow-ups",null).andExpect(status().isNotFound());assertFalse(read(pair[1],"follow-ups").toString().contains(id));}assertEquals(0,db.queryForObject("SELECT count(*) FROM reminder",Integer.class));}
 @Test void concurrentFollowupConfirmationCreatesOneReminder()throws Exception{String id=candidate(a,"Follow up in 3 months");var pool=Executors.newFixedThreadPool(2);try{var one=pool.submit(()->req(a,"POST","/api/v1/care/follow-ups/"+id+"/decision",decision("CONFIRM")).andReturn().getResponse().getStatus());var two=pool.submit(()->req(a,"POST","/api/v1/care/follow-ups/"+id+"/decision",decision("CONFIRM")).andReturn().getResponse().getStatus());assertEquals(Set.of(200,409),Set.of(one.get(),two.get()));}finally{pool.shutdownNow();}assertEquals(1,db.queryForObject("SELECT count(*) FROM reminder",Integer.class));}
 @Test void paginationAndSafeAudit()throws Exception{for(int i=0;i<21;i++)create(a,"symptoms",symptom());assertEquals(20,read(a,"symptoms").path("items").size());assertEquals(1,read(a,"symptoms?page=1").path("items").size());assertEquals(21,db.queryForObject("SELECT count(*) FROM audit_event WHERE action='SYMPTOM_CREATED'",Integer.class));String audit=db.queryForList("SELECT * FROM audit_event").toString();assertFalse(audit.contains("headache"));assertFalse(audit.contains("private synthetic"));}
 @Test void dueOffsetsAndControllableClock()throws Exception{var x=appointment(30);x.put("offsets",List.of(0,60,1440,2880,10080));var ap=create(a,"appointments",x);var rows=read(a,"reminders").path("items");for(var row:rows)assertEquals(Instant.parse(ap.path("startsAt").asText()).minusSeconds(row.path("offsetMinutes").asLong()*60),Instant.parse(row.path("scheduledAt").asText()));assertEquals(4,reminders.due().size());for(var id:reminders.due())reminders.deliver(id);assertEquals(4,read(a,"notifications").path("total").asInt());clock.advance(31);assertEquals(1,reminders.due().size());reminders.deliver(reminders.due().getFirst());assertEquals(5,read(a,"notifications").path("total").asInt());}
 @Test void exactSuggestionConfirmationRetainsEvidence()throws Exception{String id=candidate(a,"Review after 6 weeks");var x=decision("CONFIRM");x.put("confirmedAt","2026-10-13T09:00:00Z");var result=body(req(a,"POST","/api/v1/care/follow-ups/"+id+"/decision",x).andExpect(status().isOk()));assertEquals("CONFIRMED",result.path("status").asText());assertEquals(result.path("suggestedDate"),result.path("confirmedDate"));assertEquals(0,read(a,"appointments").path("total").asInt());assertEquals(1,read(a,"reminders?status=PENDING").path("total").asInt());}
 @Test void malformedAndBoundedRequests()throws Exception{req(a,"POST","/api/v1/care/symptoms",Map.of("name","x")).andExpect(status().isBadRequest());var x=symptom();x.put("notes","x".repeat(9000));req(a,"POST","/api/v1/care/symptoms",x).andExpect(status().isPayloadTooLarge());req(a,"GET","/api/v1/care/symptoms?page=-1",null).andExpect(status().isBadRequest());req(a,"GET","/api/v1/care/reminders?status=DELIVERED",null).andExpect(status().isBadRequest());}

 @Test void schedulerPollUsesPersistedRowsAndIsIdempotent()throws Exception{var x=appointment(-1);x.put("offsets",List.of(0));create(a,"appointments",x);var scheduler=new ReminderScheduler(reminders);scheduler.poll();scheduler.poll();assertEquals(1,read(a,"notifications").path("total").asInt());assertEquals("DELIVERED",read(a,"reminders").path("items").get(0).path("status").asText());}

}
