"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import Image from "next/image";
import {Button} from "@/components/ui/button";
import {shares,shareLink,shareQr,expiryOptions,type Share} from "@/lib/share-client";
import {ErrorNote,fieldClass} from "@/components/care/shared";
export function SharePanel({packId}:{packId:string}){
 const [minutes,setMinutes]=useState(30);const [created,setCreated]=useState<Share|null>(null);const [link,setLink]=useState("");const [qr,setQr]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 useEffect(()=>{if(!created)return;const id=setTimeout(()=>{setLink("");setQr("");setCreated(null);setMessage("The displayed share has expired.");},Math.max(0,Date.parse(created.expiresAt)-Date.now()));return()=>clearTimeout(id);},[created]);
 async function create(){setBusy(true);setError("");setMessage("");try{const x=await shares.create(packId,minutes);const url=shareLink(window.location.origin,x.token);setCreated(x.share);setLink(url);setQr("");try{setQr(await shareQr(url));}catch{setError("Link created, but QR rendering failed. Copy the link or revoke it below.");}}catch(e){setError(e instanceof Error?e.message:"Share creation failed.");}finally{setBusy(false);}}
 async function revoke(){if(!created)return;setBusy(true);setError("");try{await shares.revoke(created.id);setCreated(null);setLink("");setQr("");setMessage("Access revoked. Previously viewed copies cannot be recalled.");}catch(e){setError(e instanceof Error?e.message:"Revocation failed.");}finally{setBusy(false);}}
 return <section className="mb-7 border-y border-border py-5"><h2 className="text-lg font-semibold">Share temporarily</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Anyone with this link can read this generated snapshot, including its notes and source citations. Original files and your account stay private. Share only with your intended recipient.</p><ErrorNote message={error}/>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}{!created?<div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-sm">Expires after<select className={fieldClass} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}>{expiryOptions.map(x=><option key={x} value={x}>{x===1440?"24 hours":x===60?"1 hour":`${x} minutes`}</option>)}</select></label><Button disabled={busy} onClick={create}>{busy?"Creating…":"Generate temporary link"}</Button></div>:<div className="mt-4 space-y-3"><p className="text-sm">Expires {new Date(created.expiresAt).toLocaleString()}. Link shown only in this session.</p><label className="block text-sm">Private share link<input readOnly className={fieldClass} value={link} onFocus={e=>e.target.select()}/></label><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(link);setMessage("Link copied.");}catch{setError("Copy unavailable. Select and copy the link manually.");}}}>Copy link</Button><Button disabled={busy} onClick={revoke}>Revoke access</Button></div>{qr&&/* QR is a local data URL, never a remote image. */<Image unoptimized src={qr} alt="QR code for this temporary share link" width={300} height={300} className="max-w-full"/>}</div>}<Link href="/shares" className="mt-4 inline-block text-sm text-primary underline">Manage active and recent shares</Link></section>;
}
