"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { reviewClient, type ReviewCandidate, type Observation } from "@/lib/review-client";
import type { Source } from "@/lib/extraction-client";
import { label } from "@/lib/vault-client";
import { NormalizationPreview } from "./normalization-preview";
import { CorrectionDialog } from "./correction-dialog";
function VerifiedResult({ id }: { id: string }) {
  const [result, setResult] = useState<Observation | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; reviewClient.observation(id).then((r) => { if (active) setResult(r); }).catch(() => { if (active) setError("Verified result unavailable. Reload to retry."); }); return () => { active = false; }; }, [id]);
  return <div className="mt-4 border-t border-border pt-4">{error ? <p role="alert">{error}</p> : !result ? <p role="status">Loading verified result…</p> : <><h4 className="font-semibold text-primary">Verified · {new Date(result.verifiedAt).toLocaleString()}</h4><p className="my-2">{result.verified.testName} — {result.verified.value} {result.verified.unit ?? ""}</p><p className="mb-3 text-xs text-muted-foreground">Date: {result.verified.date ?? "Not supplied"} · Source flag: {result.original.abnormalFlag ?? "Not supplied"}. Original machine value: {result.original.originalValue ?? "Not read"} {result.original.originalUnit ?? ""}.</p><NormalizationPreview preview={result.normalization} />{result.correctionReason && <p className="mt-2 break-words text-sm">Verification reason: {result.correctionReason}</p>}</>}</div>;
}
export function ReviewPanel({ documentId, onSource, onChanged }: { documentId?: string; onSource?: (source: Source) => void; onChanged?: () => void }) {
  const [items, setItems] = useState<ReviewCandidate[]>([]); const [state, setState] = useState("PENDING_REVIEW"); const [page, setPage] = useState(0); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0); const [message, setMessage] = useState("");
  const [correcting, setCorrecting] = useState<ReviewCandidate | null>(null); const [rejecting, setRejecting] = useState<ReviewCandidate | null>(null); const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { const controller = new AbortController(); reviewClient.list(documentId, state, page, controller.signal).then((q) => { if (!controller.signal.aborted) { setItems(q.items); setTotal(q.total); setLoading(false); setError(""); } }).catch((e: unknown) => { if (!controller.signal.aborted) { setError(e instanceof Error ? e.message : "Review queue unavailable."); setLoading(false); } }); return () => controller.abort(); }, [documentId, state, page, revision]);
  useEffect(() => { if (rejecting) dialog.current?.showModal(); }, [rejecting]);
  function refresh() { setLoading(true); setRevision((v) => v + 1); }
  function saved() { setCorrecting(null); setRejecting(null); setMessage("Review saved. The original extraction and source are preserved."); refresh(); onChanged?.(); }
  async function act(c: ReviewCandidate, action: "confirm" | "reject") { setBusy(true); setError(""); try { if (action === "confirm") await reviewClient.confirm(c.id, c.version); else await reviewClient.reject(c.id, c.version, null); saved(); } catch (e) { setError(e instanceof Error ? e.message : "Review could not be saved."); } finally { setBusy(false); } }
  return <section className="mt-7" aria-label="Human verification"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">Review results</h3><p className="mt-1 text-sm text-muted-foreground">Check each reading against its source. Normalization alone never verifies a result.</p></div><label className="text-sm">Show<select className="ml-2 rounded-md border border-border bg-white p-2" value={state} onChange={(e) => { setState(e.target.value); setPage(0); setLoading(true); }}>{["PENDING_REVIEW", "CONFIRMED", "CORRECTED_AND_CONFIRMED", "REJECTED"].map((s) => <option key={s} value={s}>{label(s)}</option>)}</select></label></div>
    {message && <p role="status" className="mt-4 text-sm text-primary">{message} Select Confirmed or Corrected and confirmed to view verified observations.</p>}{error && <p role="alert" className="mt-4 text-red-800">{error} <button className="underline" onClick={refresh}>Reload</button></p>}
    {loading ? <div role="status" className="mt-5 h-36 rounded-lg bg-muted motion-safe:animate-pulse"><span className="sr-only">Loading review queue</span></div> : !items.length ? <p className="my-6 rounded-lg border border-dashed border-border p-6 text-sm text-muted-foreground">No {label(state).toLowerCase()} results on this page. {page > 0 ? "Go to the previous page." : "Results appear here after document processing."}</p> : <div className="mt-5 space-y-5">{items.map((c) => <article key={c.id} className="rounded-xl border border-border bg-white p-4 sm:p-5"><div className="flex flex-wrap justify-between gap-2"><h4 className="font-semibold">{c.extracted.originalTestName}</h4><span className="text-xs text-muted-foreground">{label(c.state)} · {label(c.extracted.confidence)} extraction confidence</span></div><p className="mt-3 text-xs font-medium uppercase tracking-wide text-muted-foreground">Extracted · original machine reading</p><p className="mt-1 text-lg tabular-nums">{c.extracted.originalValue ?? "Not read"} {c.extracted.originalUnit ?? "(unit not supplied)"}</p><p className="mt-1 text-sm text-muted-foreground">Reference: {c.extracted.referenceText ?? "Not supplied"} · Source flag: {c.extracted.abnormalFlag ?? "Not supplied"}</p>
      {c.state === "PENDING_REVIEW" && <><div className="mt-4"><NormalizationPreview preview={c.decision.preview} /></div>{!c.decision.canConfirm && <p className="mt-3 text-sm text-amber-900">CarePath couldn&apos;t confidently verify this result. Review the source before correcting or rejecting. {c.decision.reasons.map(label).join(" · ")}</p>}</>}
      <details className="mt-4 text-sm"><summary className="cursor-pointer font-medium">{c.filename} · page {c.extracted.source.page} · evidence</summary><pre className="mt-2 whitespace-pre-wrap break-words rounded bg-muted p-3 font-sans">{c.extracted.source.text}</pre></details><div className="mt-4 flex flex-wrap gap-2">{onSource ? <Button variant="outline" size="sm" onClick={() => onSource(c.extracted.source)}>View source · page {c.extracted.source.page}</Button> : <Link className="rounded-md border border-border px-3 py-2 text-sm text-primary" href={`/records/${encodeURIComponent(c.documentId)}?candidate=${encodeURIComponent(c.id)}`}>View source · page {c.extracted.source.page}</Link>}{c.state === "PENDING_REVIEW" && <><Button size="sm" disabled={busy || !c.decision.canConfirm} onClick={() => act(c, "confirm")}>Confirm reading</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => setCorrecting(c)}>Correct / verify</Button><Button size="sm" variant="outline" disabled={busy} onClick={() => setRejecting(c)}>Reject</Button></>}</div>{c.observationId && <VerifiedResult id={c.observationId} />}</article>)}</div>}
    <div className="mt-5 flex items-center justify-between gap-3 text-sm"><Button variant="outline" size="sm" disabled={loading || page === 0} onClick={() => { setPage((p) => p - 1); setLoading(true); }}>Previous</Button><span>{total} results · page {page + 1}</span><Button variant="outline" size="sm" disabled={loading || (page + 1) * 10 >= total} onClick={() => { setPage((p) => p + 1); setLoading(true); }}>Next</Button></div>
    {correcting && <CorrectionDialog candidate={correcting} onClose={() => setCorrecting(null)} onSaved={saved} />}{rejecting && <dialog ref={dialog} onCancel={(e) => { if (busy) e.preventDefault(); }} onClose={() => setRejecting(null)} aria-labelledby="reject-title" className="m-auto w-[min(92vw,440px)] rounded-xl border border-border bg-white p-6 text-foreground backdrop:bg-black/40"><h3 id="reject-title" className="text-xl font-semibold">Reject this candidate?</h3><p className="my-4 text-sm">It will not become a trusted observation. The original document and extraction stay available. This decision cannot be reopened in this version.</p>{error && <p role="alert" className="my-3 text-red-800">{error}</p>}<div className="flex justify-end gap-3"><Button variant="outline" disabled={busy} onClick={() => dialog.current?.close()}>Cancel</Button><Button disabled={busy} onClick={() => act(rejecting, "reject")}>Reject candidate</Button></div></dialog>}
  </section>;
}
