package com.carepath.assistant;
import static com.carepath.assistant.AssistantDtos.*;
import static com.carepath.audit.AuditService.Action.*;
import java.util.*;
import java.util.concurrent.Semaphore;
import org.springframework.stereotype.Service;
import org.slf4j.*;
import com.carepath.audit.AuditService;
import com.carepath.security.*;
@Service
public class AssistantService {
 private final StructuredRetrieval retrieval;private final RecordSafety safety;private final HealthExplanationProvider provider;private final ExplanationValidator validator;private final AuditService audit;private final Ownership ownership;private final RateLimitStore limits;private final Semaphore slots=new Semaphore(2);private static final Logger log=LoggerFactory.getLogger(AssistantService.class);
 public AssistantService(StructuredRetrieval r,RecordSafety s,HealthExplanationProvider p,ExplanationValidator v,AuditService a,Ownership o,RateLimitStore l){retrieval=r;safety=s;provider=p;validator=v;audit=a;ownership=o;limits=l;}
 public Map<String,Object> config(){return Map.of("providerAvailable",provider.available(),"maxQuestionLength",1000,"maxObservations",12,"privacy","AI is optional. With your per-request permission, selected measurement facts, dates and computed changes leave CarePath. No raw question, document text, names, filenames, account IDs or source database IDs are sent. No conversation history is stored.");}
 public Answer ask(Ask ask){
  String classification=safety.classify(ask.question());audit.assistant(ownership.currentOwnerId(),AI_EXPLANATION_REQUESTED,"SUCCESS",null);
  if(!classification.equals("RECORD"))return new Answer(classification,"NOT_CALLED",classification.equals("URGENT")?RecordSafety.URGENT:RecordSafety.BOUNDARY,"This limited English safety check is not medical triage.",List.of(),List.of(),List.of(),List.of(),classification.equals("URGENT")?RecordSafety.REFERENCES:List.of());
  var found=retrieval.retrieve(ask);if(found.context().facts().isEmpty())return new Answer("INSUFFICIENT_EVIDENCE","NOT_CALLED","No supported verified answer is available.",found.uncertainty(),List.of(),List.of(),List.of(),List.of(),List.of());
  List<String> text=found.context().facts().stream().map(Fact::text).toList();String state="NOT_REQUESTED",mode="DETERMINISTIC";long start=System.nanoTime();
  if(ask.useAi()){
   state="NOT_CONFIGURED";
   if(provider.available()){
    boolean allowed=false;try{allowed=limits.allow("carepath:assistant:"+ownership.currentOwnerId(),10,60);}catch(RuntimeException e){state="LIMITER_UNAVAILABLE";}
    if(!allowed && !state.equals("LIMITER_UNAVAILABLE"))state="RATE_LIMITED";
    if(allowed){if(!slots.tryAcquire())state="BUSY";else try{text=validator.validate(found.context(),provider.explain(found.context()));state="AVAILABLE";mode="AI_CONSTRAINED";}catch(HealthExplanationProvider.ProviderFailure e){state=e.code();}finally{slots.release();}}
   }
   if(!state.equals("AVAILABLE"))audit.assistant(ownership.currentOwnerId(),AI_PROVIDER_FAILED,"FAILURE",null);
   log.info("Record explanation provider outcome={} durationMs={}",state,(System.nanoTime()-start)/1_000_000);
  }
  if(!retrieval.stillCurrent(found.sources()))return new Answer("INSUFFICIENT_EVIDENCE","SOURCE_CHANGED","The selected records changed. Ask again to use current verified information.","No previous answer was retained.",List.of(),List.of(),List.of(),List.of(),List.of());
  return new Answer(mode,state,mode.equals("AI_CONSTRAINED")?"AI selected approved, evidence-linked wording. All medical facts are computed by CarePath.":"Record explanation generated by deterministic CarePath rules.",found.uncertainty(),found.context().facts(),found.sources(),text,found.suggestions(),List.of());
 }
}
