import { authClient } from "./auth-client.ts";
export const categories = { HOSPITAL: "Hospitals", CLINIC: "Clinics", PHARMACY: "Pharmacies", DIAGNOSTIC_CENTER: "Diagnostic centres" };
export type Category = keyof typeof categories;
export type Facility = { providerId: string; name: string; category: Category; address: string | null; distanceMeters: number | null; phone: string | null; openNow: boolean | null; hours: string[]; website: string | null; directions: string | null; bookingUrl: string | null; attributions: { name: string; url: string | null }[] };
export function safeWeb(value: string | null): string | undefined { try { const u = new URL(value ?? ""); return ["http:", "https:"].includes(u.protocol) && !u.username && !u.password ? u.href : undefined; } catch { return undefined; } }
export function requestLocation(geo: Pick<Geolocation, "getCurrentPosition"> | undefined): Promise<{ latitude: number; longitude: number }> {
 return new Promise((resolve, reject) => { if (!geo) { reject(new Error("Location is unavailable. Enter coordinates manually.")); return; } geo.getCurrentPosition(p => resolve({ latitude: p.coords.latitude, longitude: p.coords.longitude }), () => reject(new Error("Location permission was denied or location is unavailable. Enter coordinates manually or retry.")), { enableHighAccuracy: false, timeout: 10000, maximumAge: 0 }); });
}
async function request<T>(path: string, body?: unknown): Promise<T> { const r = await authClient.api(`/api/v1/nearby-care/${path}`, body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {}); if (!r.ok) throw new Error(r.status === 429 ? "Search limit reached. Wait a minute and retry." : r.status === 400 ? "Check coordinates and radius." : "Nearby Care is unavailable. Provider configuration may be required. Please retry later."); return r.json() as Promise<T>; }
export const nearby = { config: () => request<{ available: boolean }>("config"), search: (latitude: number, longitude: number, radiusMeters: number, category: Category) => request<{ results: Facility[] }>("search", { latitude, longitude, radiusMeters, category, locationConsent: true }) };
