import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync,existsSync} from "node:fs";
import {authClient,createAuthClient} from "./auth-client.ts";
import {workspace,resultLink,timelineLink,onboardingSteps,type SearchResult} from "./workspace-client.ts";
import {privacySections} from "./privacy-content.ts";

test("search uses a bounded body and never sends ownership or health terms in URL",async()=>{const old=authClient.api;let path="",init:RequestInit|undefined;authClient.api=async(p,i)=>{path=p;init=i;return new Response('{"items":[],"total":0}');};try{await workspace.search({q:"September prescription",kind:"DOCUMENT",provider:"Lab",from:"2026-09-01",to:"2026-09-30",page:2,...{owner:"foreign"}});assert.equal(path,"/api/v1/search");assert.equal(init?.method,"POST");assert.deepEqual(JSON.parse(String(init?.body)),{q:"September prescription",kind:"DOCUMENT",provider:"Lab",from:"2026-09-01",to:"2026-09-30",page:2});}finally{authClient.api=old;}});
test("activity supports category and page without resource tokens",async()=>{const old=authClient.api;let path="";authClient.api=async(p)=>{path=p;return new Response('{"items":[],"total":0}');};try{await workspace.activity("SECURITY",2);assert.equal(path,"/api/v1/activity?category=SECURITY&page=2");}finally{authClient.api=old;}});
test("workspace provider and database failures use safe errors",async()=>{const old=authClient.api;authClient.api=async()=>new Response("private SQL secret",{status:503});try{await assert.rejects(workspace.activity(),e=>e instanceof Error&&!e.message.includes("SQL"));await assert.rejects(workspace.search({q:"",kind:"ALL",provider:"",from:"",to:"",page:0}),e=>e instanceof Error&&!e.message.includes("secret"));}finally{authClient.api=old;}});
test("search links preserve exact protected observation evidence",()=>{const r:SearchResult={kind:"OBSERVATION",id:"obs",title:"Hb",date:null,provider:null,summary:"12.1",documentId:"doc/a",candidateId:"candidate/b"};assert.equal(resultLink(r),"/records/doc%2Fa?candidate=candidate%2Fb");assert.equal(resultLink({...r,kind:"APPOINTMENT",id:"a/b"}),"/appointments?id=a%2Fb");assert.equal(resultLink({...r,kind:"SYMPTOM",id:"s/b"}),"/symptoms?id=s%2Fb");});
test("timeline care links do not grant document or observation authority",()=>{const event={type:"APPOINTMENT",id:"a/b",date:"2026-09-30",title:"Clinic",observation:null,documentId:null};assert.equal(timelineLink(event),"/appointments?id=a%2Fb");assert.equal(timelineLink({...event,type:"FOLLOW_UP"}),"/follow-ups?id=a%2Fb");});
test("onboarding is nonblocking and all suggested paths exist",()=>{assert.equal(onboardingSteps.length,4);for(const step of onboardingSteps){assert.ok(existsSync(`src/app${step.href}/page.tsx`));}const page=readFileSync("src/app/onboarding/page.tsx","utf8");assert.match(page,/never blocks/);assert.match(page,/not an AI doctor/);assert.doesNotMatch(page,/localStorage|geolocation|fetch\(/);const form=readFileSync("src/components/auth/auth-form.tsx","utf8");assert.match(form,/href="\/onboarding"/);assert.doesNotMatch(form,/later phase/);});
test("privacy copy distinguishes historical copies, external consent and medical limits",()=>{const text=privacySections.map(s=>s.text).join(" ");assert.match(text,/delete those packs separately/);assert.match(text,/Revocation cannot recall/);assert.match(text,/per-request consent/);assert.match(text,/does not persist precise/);assert.match(text,/does not diagnose/);});
test("settings has real navigation and no invented preference toggles",()=>{const page=readFileSync("src/components/workspace/settings.tsx","utf8");assert.doesNotMatch(page,/type="checkbox"|role="switch"/);assert.match(page,/Email delivery is not configured/);assert.match(page,/Account details are read-only/);for(const route of ["activity","search","settings"]){assert.match(readFileSync(`src/app/${route}/layout.tsx`,"utf8"),/ProtectedShell/);}});
test("new workspace routes use the authenticated client and preserve bearer restrictions",async()=>{const paths:string[]=[];const client=createAuthClient(async(p,i)=>{paths.push(String(p));if(String(p).endsWith("refresh"))return new Response(JSON.stringify({accessToken:"synthetic",expiresIn:300,user:{id:"u",displayName:"Synthetic",email:"s@example.invalid"}}));assert.equal(new Headers(i?.headers).get("Authorization"),"Bearer synthetic");return new Response("{}");});await client.api("/api/v1/activity");await client.api("/api/v1/search",{method:"POST"});assert.equal(paths.length,3);await assert.rejects(client.api("https://evil.invalid/api/v1/search"));});
test("symptom deep links fetch the selected owner-scoped record and refresh mutations",()=>{const source=readFileSync("src/components/care/symptoms.tsx","utf8");assert.match(source,/care\.symptom\(id\)/);assert.match(source,/setSelected\(saved\)/);assert.match(source,/setSelected\(null\)/);assert.match(source,/rows\.map/);});
